# -*- coding: utf-8 -*-
"""ABC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9WSCxOgCsYCc2iXAOZ4zUNHZemAQIcT
"""

import re
from pathlib import Path


# ============================================================
# 1. SOURCE AND DESTINATION FOLDERS
# ============================================================

SOURCE_DIR = Path(
    r"C:\Users\mm7453\OneDrive - Health\workplace\adhoc\SOBs\all_md_files"
)

# cleaned_md_files will be created beside all_md_files
DEST_DIR = SOURCE_DIR.parent / "cleaned_md_files"

DEST_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 2. REMOVE LARGE NOISE SECTIONS
# ============================================================

def remove_large_noise_sections(text):
    """
    Remove large boilerplate sections that are not useful for RAG.
    """

    # Normalize line endings
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    sections_to_remove = [
        "Language Assistance Services",
        "General Notice About Nondiscrimination",
        "General List of Exclusions",
    ]

    for section in sections_to_remove:

        pattern = (
            rf"(?ims)"
            rf"^#+[ \t]*{re.escape(section)}[ \t]*$"
            rf".*?"
            rf"(?=^#+[ \t]+\S|\Z)"
        )

        text, count = re.subn(
            pattern,
            "",
            text
        )

        print(
            f"    {section}: removed {count} occurrence(s)"
        )

    return text


# ============================================================
# 3. REMOVE REPEATED HEADERS
# ============================================================

def remove_repeated_headers(text):
    """
    Remove repeated document-specific Markdown headings.
    """

    repeated_header_patterns = [
        r"(?im)^#+\s*PEDIATRIC DENTAL RIDER.*$",
        r"(?im)^#+\s*BEST BUY HMO.*$",
        r"(?im)^#+\s*VISIONCARE.*$",
    ]

    for pattern in repeated_header_patterns:

        text = re.sub(
            pattern,
            "",
            text
        )

    return text


# ============================================================
# 4. REMOVE PAGE / COMPANY ARTIFACTS
# ============================================================

def remove_page_artifacts(text):
    """
    Remove repeated company names and page artifacts.
    """

    patterns = [
        r"(?im)^\s*Harvard Pilgrim Health Care\s*$",
        r"(?im)^\s*Harvard Pilgrim Health Care,\s*Inc\.\s*$",
        r"(?im)^\s*Harvard Pilgrim Health Care of New England,\s*Inc\.\s*$",
    ]

    for pattern in patterns:

        text = re.sub(
            pattern,
            "",
            text
        )

    return text


# ============================================================
# 5. REMOVE MARKDOWN LINKS BUT KEEP LABEL TEXT
# ============================================================

def remove_markdown_links(text):
    """
    Example:

    [Member Portal](https://example.com)

    becomes:

    Member Portal
    """

    text = re.sub(
        r"\[([^\]]+)\]\((.*?)\)",
        r"\1",
        text
    )

    return text


# ============================================================
# 6. REMOVE CONSECUTIVE DUPLICATE LINES
# ============================================================

def remove_duplicate_lines(text):
    """
    Remove immediately repeated duplicate lines.
    """

    lines = text.splitlines()

    deduped = []

    for line in lines:

        current_line = line.strip()

        if not deduped:
            deduped.append(line)
            continue

        previous_line = deduped[-1].strip()

        if current_line != previous_line:
            deduped.append(line)

    return "\n".join(deduped)


# ============================================================
# 7. CLEAN WHITESPACE
# ============================================================

def clean_whitespace(text):
    """
    Remove unnecessary whitespace and excessive blank lines.
    """

    # Remove trailing spaces
    text = re.sub(
        r"[ \t]+$",
        "",
        text,
        flags=re.MULTILINE
    )

    # Replace 3 or more blank-line areas with 1 blank line
    text = re.sub(
        r"\n\s*\n\s*\n+",
        "\n\n",
        text
    )

    return text.strip()


# ============================================================
# 8. MAIN MARKDOWN CLEANING FUNCTION
# ============================================================

def clean_markdown(text):
    """
    Perform generic Markdown cleaning for RAG preprocessing.
    """

    # Normalize line endings
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    # Remove company/page artifacts
    text = remove_page_artifacts(text)

    # Remove repeated document headers
    text = remove_repeated_headers(text)

    # Remove Markdown URLs but retain label text
    text = remove_markdown_links(text)

    # Remove duplicate lines
    text = remove_duplicate_lines(text)

    # Clean excessive whitespace
    text = clean_whitespace(text)

    return text


# ============================================================
# 9. VALIDATE CLEANING
# ============================================================

def validate_cleaning(text):
    """
    Check if unwanted boilerplate sections still remain.
    """

    sections_to_check = [
        "Language Assistance Services",
        "General Notice About Nondiscrimination",
        "General List of Exclusions",
    ]

    remaining_sections = []

    for section in sections_to_check:

        if section.lower() in text.lower():
            remaining_sections.append(section)

    return remaining_sections


# ============================================================
# 10. PROCESS SINGLE FILE
# ============================================================

def process_single_file(file_path):
    """
    Process and save one Markdown file.
    """

    print("\n" + "=" * 70)
    print(f"Processing: {file_path.name}")

    # Read original file
    text = file_path.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    original_length = len(text)

    # Remove large unwanted sections
    text = remove_large_noise_sections(text)

    # General Markdown cleaning
    cleaned_text = clean_markdown(text)

    # Validate cleaning
    remaining_sections = validate_cleaning(
        cleaned_text
    )

    # Output file path
    output_file = DEST_DIR / file_path.name

    # Save cleaned Markdown
    output_file.write_text(
        cleaned_text,
        encoding="utf-8"
    )

    cleaned_length = len(cleaned_text)

    removed_length = (
        original_length - cleaned_length
    )

    print(
        f"    Original characters : {original_length:,}"
    )

    print(
        f"    Cleaned characters  : {cleaned_length:,}"
    )

    print(
        f"    Removed characters  : {removed_length:,}"
    )

    if remaining_sections:

        print(
            "    WARNING: Unwanted sections still remain:"
        )

        for section in remaining_sections:
            print(
                f"      - {section}"
            )

    else:

        print(
            "    Validation OK"
        )

    print(
        f"    Saved to: {output_file}"
    )


# ============================================================
# 11. PROCESS ALL FILES
# ============================================================

def process_files():
    """
    Process all Markdown files in SOURCE_DIR.
    """

    md_files = list(
        SOURCE_DIR.glob("*.md")
    )

    print(
        "=" * 70
    )

    print(
        "MARKDOWN PREPROCESSING FOR RAG"
    )

    print(
        "=" * 70
    )

    print(
        f"\nSource directory:\n{SOURCE_DIR}"
    )

    print(
        f"\nDestination directory:\n{DEST_DIR}"
    )

    print(
        f"\nFound {len(md_files)} Markdown files."
    )

    if len(md_files) == 0:

        print(
            "\nNo Markdown files found."
        )

        return

    successful = 0
    failed = 0

    for file_path in md_files:

        try:

            process_single_file(
                file_path
            )

            successful += 1

        except Exception as e:

            failed += 1

            print(
                f"\nERROR processing: {file_path.name}"
            )

            print(
                f"    Error type: {type(e).__name__}"
            )

            print(
                f"    Error: {e}"
            )

    # ========================================================
    # FINAL SUMMARY
    # ========================================================

    print(
        "\n" + "=" * 70
    )

    print(
        "PROCESS COMPLETED"
    )

    print(
        "=" * 70
    )

    print(
        f"Total files : {len(md_files)}"
    )

    print(
        f"Successful  : {successful}"
    )

    print(
        f"Failed      : {failed}"
    )

    print(
        f"\nCleaned files saved to:\n{DEST_DIR}"
    )


# ============================================================
# 12. ENTRY POINT
# ============================================================

if __name__ == "__main__":

    process_files()
