# -*- coding: utf-8 -*-
"""ABC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9WSCxOgCsYCc2iXAOZ4zUNHZemAQIcT
"""

import re
from pathlib import Path


# ============================================================
# 1. SOURCE AND DESTINATION FOLDERS
# ============================================================

SOURCE_DIR = Path(
    r"C:\Users\mm7453\OneDrive - Health\workplace\adhoc\SOBs\all_md_files"
)

DEST_DIR = SOURCE_DIR.parent / "cleaned_md_files"

DEST_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 2. REMOVE LARGE BOILERPLATE / NOISE SECTIONS
# ============================================================

def remove_large_noise_sections(text):
    """
    Remove large unwanted sections from Markdown documents.

    Sections currently removed:
    - Language Assistance Services
    - General Notice About Nondiscrimination
    - General List of Exclusions
    """

    # Normalize line endings
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    sections_to_remove = [
        "Language Assistance Services",
        "General Notice About Nondiscrimination",
        "General List of Exclusions",
    ]

    for section in sections_to_remove:

        pattern = (
            rf"(?ims)"
            rf"^#+[ \t]*{re.escape(section)}[ \t]*$"
            rf".*?"
            rf"(?=^#+[ \t]+\S|\Z)"
        )

        text, count = re.subn(
            pattern,
            "",
            text
        )

        if count > 0:
            print(
                f"    Removed section "
                f"'{section}' -> {count} occurrence(s)"
            )

    return text


# ============================================================
# 3. REMOVE SPECIFIC DOCUMENT BANNERS / HEADERS
# ============================================================

def remove_repeated_headers(text):
    """
    Remove document-specific repeated headings or page banners.
    Add more patterns here when you discover common repeated noise.
    """

    repeated_header_patterns = [

        # Pediatric Dental Rider
        r"(?im)^#+\s*PEDIATRIC DENTAL RIDER.*$",

        # Best Buy HMO
        r"(?im)^#+\s*BEST BUY HMO.*$",

        # VisionCare
        r"(?im)^#+\s*VISIONCARE.*$",
    ]

    for pattern in repeated_header_patterns:

        text = re.sub(
            pattern,
            "",
            text
        )

    return text


# ============================================================
# 4. REMOVE ORGANIZATION / PAGE ARTIFACTS
# ============================================================

def remove_page_artifacts(text):
    """
    Remove recurring organization names or page artifacts.
    """

    patterns = [

        # Harvard Pilgrim Health Care variants
        r"(?im)^\s*Harvard Pilgrim Health Care\s*$",

        r"(?im)^\s*Harvard Pilgrim Health Care,\s*Inc\.\s*$",

        r"(?im)^\s*Harvard Pilgrim Health Care of New England,"
        r"\s*Inc\.\s*$",
    ]

    for pattern in patterns:

        text = re.sub(
            pattern,
            "",
            text
        )

    return text


# ============================================================
# 5. REMOVE MARKDOWN LINKS BUT KEEP LINK TEXT
# ============================================================

def remove_markdown_links(text):
    """
    Convert:
        [member portal](https://example.com)

    Into:
        member portal
    """

    text = re.sub(
        r"\[([^\]]+)\]\((.*?)\)",
        r"\1",
        text
    )

    return text


# ============================================================
# 6. REMOVE DUPLICATE CONSECUTIVE LINES
# ============================================================

def remove_duplicate_lines(text):
    """
    Remove immediately repeated duplicate lines.

    Example:

    Benefits
    Benefits

    becomes:

    Benefits
    """

    lines = text.splitlines()

    deduped = []

    for line in lines:

        current = line.strip()

        if not deduped:
            deduped.append(line)
            continue

        previous = deduped[-1].strip()

        if current != previous:
            deduped.append(line)

    return "\n".join(deduped)


# ============================================================
# 7. CLEAN WHITESPACE
# ============================================================

def clean_whitespace(text):
    """
    Clean excessive blank lines and whitespace.
    """

    # Remove trailing spaces from every line
    text = re.sub(
        r"[ \t]+$",
        "",
        text,
        flags=re.MULTILINE
    )

    # Convert tabs / repeated spaces to single space
    # but preserve Markdown indentation as much as possible
    text = re.sub(
        r"[ \t]{2,}",
        " ",
        text
    )

    # More than 2 newlines -> 2 newlines
    text = re.sub(
        r"\n\s*\n\s*\n+",
        "\n\n",A
        text
    )

    return text.strip()


# ============================================================
# 8. MAIN MARKDOWN CLEANING FUNCTION
# ============================================================

def clean_markdown(text):
    """
    Generic Markdown cleaning before RAG chunking/indexing.
    """

    # --------------------------------------------------------
    # Normalize line endings
    # --------------------------------------------------------

    text = text.replace(
        "\r\n",
        "\n"
    )

    text = text.replace(
        "\r",
        "\n"
    )

    # --------------------------------------------------------
    # Remove page/document artifacts
    # --------------------------------------------------------

    text = remove_page_artifacts(text)

    # --------------------------------------------------------
    # Remove known repeated document headers
    # --------------------------------------------------------

    text = remove_repeated_headers(text)

    # --------------------------------------------------------
    # Remove Markdown URLs but retain readable label
    # --------------------------------------------------------

    text = remove_markdown_links(text)

    # --------------------------------------------------------
    # Remove duplicate consecutive lines
    # --------------------------------------------------------

    text = remove_duplicate_lines(text)

    # --------------------------------------------------------
    # Clean whitespace
    # --------------------------------------------------------

    text = clean_whitespace(text)

    return text


# ============================================================
# 9. VALIDATION FUNCTION
# ============================================================

def validate_cleaning(text):
    """
    Check whether unwanted sections remain after cleaning.
    """

    unwanted_sections = [
        "Language Assistance Services",
        "General Notice About Nondiscrimination",
        "General List of Exclusions",
    ]

    remaining = []

    for section in unwanted_sections:

        if section.lower() in text.lower():
            remaining.append(section)

    return remaining


# ============================================================
# 10. PROCESS ONE FILE
# ============================================================

def process_single_file(file_path):
    """
    Process a single Markdown file.
    """

    print(
        f"\nProcessing: {file_path.name}"
    )

    # --------------------------------------------------------
    # Read original Markdown
    # --------------------------------------------------------

    text = file_path.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    original_length = len(text)

    # --------------------------------------------------------
    # STEP 1:
    # Remove large boilerplate sections FIRST
    # --------------------------------------------------------

    text = remove_large_noise_sections(
        text
    )

    # --------------------------------------------------------
    # STEP 2:
    # General Markdown cleanup
    # --------------------------------------------------------

    cleaned_text = clean_markdown(
        text
    )

    # --------------------------------------------------------
    # STEP 3:
    # Validation
    # --------------------------------------------------------

    remaining_sections = validate_cleaning(
        cleaned_text
    )

    # --------------------------------------------------------
    # STEP 4:
    # Save cleaned Markdown
    # --------------------------------------------------------

    output_file = (
        DEST_DIR / file_path.name
    )

    output_file.write_text(
        cleaned_text,
        encoding="utf-8"
    )

    cleaned_length = len(cleaned_text)

    reduction = (
        original_length -
        cleaned_length
    )

    print(
        f"    Original chars : {original_length:,}"
    )

    print(
        f"    Cleaned chars  : {cleaned_length:,}"
    )

    print(
        f"    Removed chars  : {reduction:,}"
    )

    # --------------------------------------------------------
    # Validation reporting
    # --------------------------------------------------------

    if remaining_sections:

        print(
            "    WARNING: Some unwanted "
            "sections still remain:"
        )

        for section in remaining_sections:
            print(
                f"       - {section}"
            )

    else:

        print(
            "    Validation OK: "
            "noise sections removed"
        )

    print(
        f"    Saved -> {output_file}"
    )


# ============================================================
# 11. PROCESS ALL FILES
# ============================================================

def process_files():
    """
    Process all Markdown files from SOURCE_DIR.
    """

    md_files = list(
        SOURCE_DIR.glob("*.md")
    )

    print(
        "=" * 70
    )

    print(
        "MARKDOWN CLEANING PIPELINE"
    )

    print(
        "=" * 70
    )

    print(
        f"Source folder      : {SOURCE_DIR}"
    )

    print(
        f"Destination folder : {DEST_DIR}"
    )

    print(
        f"Found {len(md_files)} Markdown files"
    )

    if len(md_files) == 0:

        print(
            "\nNo Markdown files found."
        )

        return

    successful = 0
    failed = 0

    for file_path in md_files:

        try:

            process_single_file(
                file_path
            )

            successful += 1

        except Exception as e:

            failed += 1

            print(
                f"\nERROR processing "
                f"{file_path.name}"
            )

            print(
                f"    {type(e).__name__}: {e}"
            )

    # --------------------------------------------------------
    # Final summary
    # --------------------------------------------------------

    print(
        "\n" + "=" * 70
    )

    print(
        "PROCESSING COMPLETED"
    )

    print(
        "=" * 70
    )

    print(
        f"Total files : {len(md_files)}"
    )

    print(
        f"Successful  : {successful}"
    )

    print(
        f"Failed      : {failed}"
    )

    print(
        f"\nCleaned files saved to:\n{DEST_DIR}"
    )


# ============================================================
# 12. OPTIONAL DEBUG FUNCTION FOR ONE PROBLEMATIC FILE
# ============================================================

def debug_file(filename):
    """
    Use this when one particular file is not being cleaned properly.

    Example:
        debug_file("MD0000003920.md")
    """

    file_path = (
        SOURCE_DIR / filename
    )

    if not file_path.exists():

        print(
            f"File not found: {file_path}"
        )

        return

    text = file_path.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    sections = [
        "Language Assistance Services",
        "General Notice About Nondiscrimination",
        "General List of Exclusions",
    ]

    print(
        "\n" + "=" * 70
    )

    print(
        f"DEBUGGING: {filename}"
    )

    print(
        "=" * 70
    )

    print(
        "\nBEFORE CLEANING"
    )

    for section in sections:

        present = (
            section.lower()
            in text.lower()
        )

        print(
            f"{section}: {present}"
        )

    # --------------------------------------------------------
    # Display exact matching lines
    # --------------------------------------------------------

    print(
        "\nExact heading lines found:"
    )

    for line in text.splitlines():

        lower_line = line.lower()

        if (
            "language assistance" in lower_line
            or "nondiscrimination" in lower_line
            or "general list of exclusions" in lower_line
        ):

            print(
                repr(line)
            )

    # --------------------------------------------------------
    # Run cleaning
    # --------------------------------------------------------

    cleaned = remove_large_noise_sections(
        text
    )

    cleaned = clean_markdown(
        cleaned
    )

    print(
        "\nAFTER CLEANING"
    )

    for section in sections:

        present = (
            section.lower()
            in cleaned.lower()
        )

        print(
            f"{section}: {present}"
        )


# ============================================================
# 13. PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":

    process_files()

    # --------------------------------------------------------
    # Uncomment this ONLY when debugging MD0000003920
    # --------------------------------------------------------

    # debug_file("MD0000003920.md")
