# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W0ubkpSCi5VMTw4A-g34hEFMYY3iQeKz
"""

# -*- coding: utf-8 -*-

import re
from pathlib import Path


# ============================================================
# 1. SOURCE AND DESTINATION FOLDERS
# ============================================================

SOURCE_DIR = Path(
    r"C:\Users\mm7453\OneDrive - Health\workplace\adhoc\SOBs\all_md_files"
)

# cleaned_md_files will be created beside all_md_files
DEST_DIR = SOURCE_DIR.parent / "cleaned_md_files"

DEST_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 2. REMOVE LARGE NOISE SECTIONS
# ============================================================

def remove_large_noise_sections(text):
    """
    Remove complete unwanted boilerplate sections.

    Important:
    - Removes the target heading.
    - Removes all nested subheadings and content below it.
    - Stops only when another heading of the same or higher
      Markdown level is found.

    Example:

    ### General List of Exclusions MASSACHUSETTS
    #### Exclusion
    ##### Alternative Treatments
    ##### Dental Services

    All of the above will be removed as one section.
    """

    # Normalize line endings
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    # Partial heading patterns.
    # .* allows suffixes such as:
    #
    # General Notice About Nondiscrimination and Accessibility Requirements
    # General List of Exclusions MASSACHUSETTS
    #
    target_patterns = [
        r"Language Assistance Services.*",
        r"General Notice About Nondiscrimination.*",
        r"General List of Exclusions.*",
    ]

    for target in target_patterns:

        removed_count = 0

        # Find target Markdown heading
        heading_pattern = re.compile(
            rf"(?im)^(?P<hashes>#+)[ \t]*{target}[ \t]*$"
        )

        while True:

            match = heading_pattern.search(text)

            if not match:
                break

            heading_level = len(
                match.group("hashes")
            )

            section_start = match.start()

            # ------------------------------------------------
            # Find next heading of SAME or HIGHER importance
            #
            # If target heading is:
            #
            # ### General List of Exclusions
            #
            # then:
            #
            # #### Exclusion
            # ##### Dental Services
            #
            # belong inside this section.
            #
            # We stop only at:
            #
            # #
            # ##
            # ###
            # ------------------------------------------------

            remaining_text = text[
                match.end():
            ]

            next_heading_pattern = re.compile(
                rf"(?m)^#{{1,{heading_level}}}[ \t]+\S"
            )

            next_match = next_heading_pattern.search(
                remaining_text
            )

            if next_match:

                section_end = (
                    match.end()
                    + next_match.start()
                )

            else:

                # Section continues to end of document
                section_end = len(text)

            # Remove section
            text = (
                text[:section_start]
                + text[section_end:]
            )

            removed_count += 1

        print(
            f"    {target}: removed "
            f"{removed_count} occurrence(s)"
        )

    return text


# ============================================================
# 3. REMOVE REPEATED HEADERS
# ============================================================

def remove_repeated_headers(text):
    """
    Remove known repeated document-specific Markdown headings.

    These should only contain headings that are known to be
    repeated page/header artifacts and not meaningful content.
    """

    repeated_header_patterns = [
        r"(?im)^#+\s*PEDIATRIC DENTAL RIDER.*$",
        r"(?im)^#+\s*BEST BUY HMO.*$",
        r"(?im)^#+\s*VISIONCARE.*$",
    ]

    for pattern in repeated_header_patterns:

        text = re.sub(
            pattern,
            "",
            text
        )

    return text


# ============================================================
# 4. REMOVE PAGE / COMPANY ARTIFACTS
# ============================================================

def remove_page_artifacts(text):
    """
    Remove repeated standalone company-name artifacts.

    This does NOT remove company names when they appear
    naturally inside meaningful paragraphs.
    """

    patterns = [
        r"(?im)^\s*Harvard Pilgrim Health Care\s*$",
        r"(?im)^\s*Harvard Pilgrim Health Care,\s*Inc\.\s*$",
        r"(?im)^\s*Harvard Pilgrim Health Care of New England,\s*Inc\.\s*$",
    ]

    for pattern in patterns:

        text = re.sub(
            pattern,
            "",
            text
        )

    return text


# ============================================================
# 5. REMOVE PAGE METADATA COMMENTS
# ============================================================

def remove_page_metadata_comments(text):
    """
    Remove page extraction metadata such as:

    <!-- PageFooter="..." -->
    <!-- PageNumber="15" -->
    <!-- PageBreak -->

    These are extraction artifacts and usually not useful
    for semantic retrieval.
    """

    patterns = [

        # Page footer
        r'(?is)<!--\s*PageFooter\s*=.*?-->',

        # Page number
        r'(?is)<!--\s*PageNumber\s*=.*?-->',

        # Page break
        r'(?is)<!--\s*PageBreak\s*-->',

    ]

    for pattern in patterns:

        text = re.sub(
            pattern,
            "",
            text
        )

    return text


# ============================================================
# 6. REMOVE MARKDOWN LINKS BUT KEEP LABEL TEXT
# ============================================================

def remove_markdown_links(text):
    """
    Convert:

    [Member Portal](https://example.com)

    into:

    Member Portal
    """

    text = re.sub(
        r"\[([^\]]+)\]\((.*?)\)",
        r"\1",
        text
    )

    return text


# ============================================================
# 7. REMOVE CONSECUTIVE DUPLICATE PROSE LINES
# ============================================================

def remove_duplicate_lines(text):
    """
    Remove immediately repeated duplicate prose lines.

    Important:
    - HTML table content is preserved.
    - Markdown table content is preserved.
    - Duplicate removal is only applied to ordinary text.
    """

    lines = text.splitlines()

    deduped = []

    inside_html_table = False

    for line in lines:

        stripped = line.strip()

        # ----------------------------------------------------
        # HTML TABLE START
        # ----------------------------------------------------

        if re.search(
            r"<table\b",
            stripped,
            flags=re.IGNORECASE
        ):
            inside_html_table = True

        # ----------------------------------------------------
        # PRESERVE HTML TABLES
        # ----------------------------------------------------

        if inside_html_table:

            deduped.append(line)

            if re.search(
                r"</table>",
                stripped,
                flags=re.IGNORECASE
            ):
                inside_html_table = False

            continue

        # ----------------------------------------------------
        # PRESERVE MARKDOWN TABLE ROWS
        # ----------------------------------------------------

        if stripped.startswith("|"):

            deduped.append(line)

            continue

        # ----------------------------------------------------
        # FIRST LINE
        # ----------------------------------------------------

        if not deduped:

            deduped.append(line)

            continue

        previous_line = deduped[-1].strip()

        # ----------------------------------------------------
        # REMOVE ONLY IMMEDIATE EXACT DUPLICATES
        # ----------------------------------------------------

        if stripped != previous_line:

            deduped.append(line)

    return "\n".join(deduped)


# ============================================================
# 8. CLEAN WHITESPACE
# ============================================================

def clean_whitespace(text):
    """
    Remove unnecessary whitespace while retaining useful
    Markdown structure.
    """

    # Remove trailing spaces
    text = re.sub(
        r"[ \t]+$",
        "",
        text,
        flags=re.MULTILINE
    )

    # Replace 3+ blank areas with max 2 newlines
    text = re.sub(
        r"\n\s*\n\s*\n+",
        "\n\n",
        text
    )

    return text.strip()


# ============================================================
# 9. MAIN MARKDOWN CLEANING FUNCTION
# ============================================================

def clean_markdown(text):
    """
    Perform generic Markdown cleaning for RAG preprocessing.

    Important content retained:
    - Markdown headings
    - HTML tables
    - Markdown tables
    - EXTRACTED TABLES section
    - meaningful document text
    """

    # Normalize line endings
    text = text.replace(
        "\r\n",
        "\n"
    )

    text = text.replace(
        "\r",
        "\n"
    )

    # Remove page extraction metadata
    text = remove_page_metadata_comments(
        text
    )

    # Remove company/page artifacts
    text = remove_page_artifacts(
        text
    )

    # Remove known repeated document headers
    text = remove_repeated_headers(
        text
    )

    # Remove Markdown URLs but retain label text
    text = remove_markdown_links(
        text
    )

    # Remove only safe duplicate prose lines
    text = remove_duplicate_lines(
        text
    )

    # Clean excessive whitespace
    text = clean_whitespace(
        text
    )

    return text


# ============================================================
# 10. VALIDATE CLEANING
# ============================================================

def validate_cleaning(text):
    """
    Check whether unwanted large boilerplate sections
    still remain after cleaning.
    """

    sections_to_check = [
        "Language Assistance Services",
        "General Notice About Nondiscrimination",
        "General List of Exclusions",
    ]

    remaining_sections = []

    for section in sections_to_check:

        if section.lower() in text.lower():

            remaining_sections.append(
                section
            )

    return remaining_sections


# ============================================================
# 11. PROCESS SINGLE FILE
# ============================================================

def process_single_file(file_path):
    """
    Process and save one Markdown file.
    """

    print(
        "\n" + "=" * 70
    )

    print(
        f"Processing: {file_path.name}"
    )

    # --------------------------------------------------------
    # READ ORIGINAL FILE
    # --------------------------------------------------------

    text = file_path.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    original_length = len(text)

    # --------------------------------------------------------
    # REMOVE COMPLETE LARGE UNWANTED SECTIONS
    # --------------------------------------------------------

    text = remove_large_noise_sections(
        text
    )

    # --------------------------------------------------------
    # GENERAL MARKDOWN CLEANING
    # --------------------------------------------------------

    cleaned_text = clean_markdown(
        text
    )

    # --------------------------------------------------------
    # VALIDATE
    # --------------------------------------------------------

    remaining_sections = validate_cleaning(
        cleaned_text
    )

    # --------------------------------------------------------
    # OUTPUT PATH
    # --------------------------------------------------------

    output_file = (
        DEST_DIR
        / file_path.name
    )

    # --------------------------------------------------------
    # SAVE FILE
    # --------------------------------------------------------

    output_file.write_text(
        cleaned_text,
        encoding="utf-8"
    )

    cleaned_length = len(
        cleaned_text
    )

    removed_length = (
        original_length
        - cleaned_length
    )

    # --------------------------------------------------------
    # LOGGING
    # --------------------------------------------------------

    print(
        f"    Original characters : "
        f"{original_length:,}"
    )

    print(
        f"    Cleaned characters  : "
        f"{cleaned_length:,}"
    )

    print(
        f"    Removed characters  : "
        f"{removed_length:,}"
    )

    if remaining_sections:

        print(
            "    WARNING: unwanted sections "
            "still remain:"
        )

        for section in remaining_sections:

            print(
                f"      - {section}"
            )

    else:

        print(
            "    Validation OK"
        )

    print(
        f"    Saved to: {output_file}"
    )


# ============================================================
# 12. PROCESS ALL FILES
# ============================================================

def process_files():
    """
    Process all Markdown files inside SOURCE_DIR.
    """

    md_files = sorted(
        SOURCE_DIR.glob("*.md")
    )

    print(
        "=" * 70
    )

    print(
        "MARKDOWN PREPROCESSING FOR RAG"
    )

    print(
        "=" * 70
    )

    print(
        f"\nSource directory:\n{SOURCE_DIR}"
    )

    print(
        f"\nDestination directory:\n{DEST_DIR}"
    )

    print(
        f"\nFound {len(md_files)} Markdown files."
    )

    # --------------------------------------------------------
    # NO FILES FOUND
    # --------------------------------------------------------

    if len(md_files) == 0:

        print(
            "\nNo Markdown files found."
        )

        return

    successful = 0
    failed = 0

    # --------------------------------------------------------
    # PROCESS EACH FILE
    # --------------------------------------------------------

    for file_path in md_files:

        try:

            process_single_file(
                file_path
            )

            successful += 1

        except Exception as e:

            failed += 1

            print(
                f"\nERROR processing: "
                f"{file_path.name}"
            )

            print(
                f"    Error type: "
                f"{type(e).__name__}"
            )

            print(
                f"    Error: {e}"
            )

    # ========================================================
    # FINAL SUMMARY
    # ========================================================

    print(
        "\n" + "=" * 70
    )

    print(
        "PROCESS COMPLETED"
    )

    print(
        "=" * 70
    )

    print(
        f"Total files : {len(md_files)}"
    )

    print(
        f"Successful  : {successful}"
    )

    print(
        f"Failed      : {failed}"
    )

    print(
        f"\nCleaned files saved to:\n{DEST_DIR}"
    )


# ============================================================
# 13. ENTRY POINT
# ============================================================

if __name__ == "__main__":

    process_files()