# -*- coding: utf-8 -*-
"""chunking12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CV0lR7rj1b5qSzxzFmbZ7FqadIHxxmbH
"""

# -*- coding: utf-8 -*-

# ============================================================
# POINT32HEALTH SOB MARKDOWN -> RAG CHUNKS JSONL
# ============================================================
#
# DOCUMENT STRUCTURE
#
# SOB Markdown
#      │
#      ├── Document body
#      │      │
#      │      ├── prose
#      │      ├── HTML tables
#      │      └── surrounding context
#      │
#      │      -> section-aware chunks
#      │      -> HTML tables kept intact
#      │      -> chunk_type = "text"
#      │      -> content_source = "document_body"
#      │
#      └── EXTRACTED TABLES
#             │
#             └── Markdown tables
#                    ↓
#                row-aware chunks
#                    ↓
#                repeat header
#                    ↓
#                chunk_type = "table"
#                content_source = "extracted_table"
#
#
# METADATA EXTRACTED
#
# - document_id
# - chunk_id
# - plan_name
# - state
# - effective_date
# - form_number
# - product_type
# - plan_variant
# - source_file
# - h1
# - h2
# - h3
# - h4
# - section
# - section_path
# - chunk_type
# - content_source
# - table_name
# - text
# - embedding_text
#
# ============================================================


from pathlib import Path
import re
import json
from typing import Optional, Dict, List


# ============================================================
# 1. INPUT / OUTPUT CONFIGURATION
# ============================================================

INPUT_FOLDER = Path(
    r"C:\Users\mm7453\OneDrive - Point32Health\p32_workplace\adhoc\SOBs\cleaned_md_files"
)

OUTPUT_FOLDER = Path(
    r"C:\Users\mm7453\OneDrive - Point32Health\p32_workplace\adhoc\SOBs\chunked_files"
)

OUTPUT_FOLDER.mkdir(
    parents=True,
    exist_ok=True
)

OUTPUT_FILE = OUTPUT_FOLDER / "sob_chunks.jsonl"


# ============================================================
# 2. CHUNKING CONFIGURATION
# ============================================================

# Normal document-body chunk size
CHUNK_SIZE = 5000

# Applied to prose only
CHUNK_OVERLAP = 500

# Used to avoid tiny fragments created by splitting
MIN_CHUNK = 100

# Markdown table target chunk size
TABLE_CHUNK_SIZE = 5000


# ============================================================
# 3. STATES
# ============================================================

STATE_PATTERNS = {

    "MASSACHUSETTS": "Massachusetts",

    "MAINE": "Maine",

    "NEW HAMPSHIRE": "New Hampshire",

    "RHODE ISLAND": "Rhode Island",

    "CONNECTICUT": "Connecticut",

    "VERMONT": "Vermont",

    "NEW YORK": "New York",
}


# ============================================================
# 4. PRODUCT TYPE RULES
# ============================================================
#
# IMPORTANT:
#
# More specific rules appear before generic ones.
#
# ============================================================

PRODUCT_PATTERNS = [

    # --------------------------------------------------------
    # Pediatric Dental
    # --------------------------------------------------------

    (
        "Pediatric Dental",
        [
            r"\bPEDIATRIC\s+DENTAL\s+RIDER\b",
            r"\bPEDIATRIC\s+DENTAL\b",
        ]
    ),


    # --------------------------------------------------------
    # Dental
    # --------------------------------------------------------

    (
        "Dental",
        [
            r"\bDENTAL\s+RIDER\b",
            r"\bPREVENTIVE\s+DENTAL\b",
            r"\bDENTAL\s+PLAN\b",
        ]
    ),


    # --------------------------------------------------------
    # Vision
    # --------------------------------------------------------

    (
        "Vision",
        [
            r"\bVISIONCARE\b",
            r"\bVISION\s+CARE\b",
            r"\bVISION\s+BENEFIT\b",
        ]
    ),


    # --------------------------------------------------------
    # Special / Government / Dual products
    # --------------------------------------------------------

    (
        "D-SNP",
        [
            r"\bD[\s-]?SNP\b",
            r"\bDUAL\s+ELIGIBLE\s+SPECIAL\s+NEEDS\b",
        ]
    ),

    (
        "SCO",
        [
            r"\bSENIOR\s+CARE\s+OPTIONS\b",
            r"\bSCO\b",
        ]
    ),

    (
        "USFHP",
        [
            r"\bUSFHP\b",
            r"\bUNIFORMED\s+SERVICES\s+FAMILY\s+HEALTH\s+PLAN\b",
        ]
    ),


    # --------------------------------------------------------
    # Medicare
    # --------------------------------------------------------

    (
        "Medicare Enhance",
        [
            r"\bMEDICARE\s+ENHANCE\b",
        ]
    ),

    (
        "Medicare Advantage PPO",
        [
            r"\bMEDICARE\s+PREFERRED\s+PPO\b",
            r"\bMEDICARE\s+ADVANTAGE\s+PPO\b",
        ]
    ),

    (
        "Medicare Advantage HMO",
        [
            r"\bMEDICARE\s+PREFERRED\s+HMO\b",
            r"\bMEDICARE\s+ADVANTAGE\s+HMO\b",
        ]
    ),

    (
        "Medicare",
        [
            r"\bMEDICARE\b",
        ]
    ),


    # --------------------------------------------------------
    # Commercial Medical Products
    # --------------------------------------------------------

    (
        "EPO",
        [
            r"\bEPO\b",
        ]
    ),

    (
        "PPO",
        [
            r"\bPPO\b",
        ]
    ),

    (
        "POS",
        [
            r"\bPOS\b",
            r"\bPOINT[\s-]+OF[\s-]+SERVICE\b",

            # Some DPO documents explicitly identify
            # themselves as POS plans
            r"\bDPO\s+PLAN\s*\(\s*POS\s*\)",
        ]
    ),

    (
        "DPO",
        [
            r"\bDPO\b",
        ]
    ),

    (
        "GEO",
        [
            r"\bGEO\b",
        ]
    ),

    (
        "HMO",
        [
            r"\bHMO\b",
        ]
    ),
]


# ============================================================
# 5. PLAN VARIANT RULES
# ============================================================

PLAN_VARIANT_PATTERNS = {

    "HSA": [
        r"\bHSA\b"
    ],

    "CDHP": [
        r"\bCDHP\b"
    ],

    "Flex Plus": [
        r"\bFLEX\s+PLUS\b"
    ],

    "Flex": [
        r"\bFLEX\b"
    ],

    "ChoiceNet": [
        r"\bCHOICENET\b"
    ],

    "Choice Plus": [
        r"\bCHOICE\s+PLUS\b"
    ],

    "National Access": [
        r"\bNATIONAL\s+ACCESS\b"
    ],

    "Tiered": [
        r"\bTIERED\b"
    ],

    "Quality": [
        r"\bQUALITY\b"
    ],

    "Focus Network": [
        r"\bFOCUS\s+NETWORK\b"
    ],

    "Network Premier": [
        r"\bNETWORK\s+PREMIER\b"
    ],

    "Domestic and Community": [
        r"\bDOMESTIC\s+AND\s+COMMUNITY\b"
    ],

    "Out of Area": [
        r"\bOUT\s+OF\s+AREA\b"
    ],

    "Explorer": [
        r"\bEXPLORER\b"
    ],

    "Best Buy": [
        r"\bBEST\s+BUY\b"
    ],

    "Maine's Choice Plus": [
        r"\bMAINE['’]S\s+CHOICE\s+PLUS\b"
    ],

    "Littleton Options": [
        r"\bLITTLETON\s+OPTIONS\b"
    ],

    "myClassic": [
        r"\bMYCLASSIC\b"
    ],

    "myAdvantage": [
        r"\bMYADVANTAGE\b"
    ],

    "ElevateHealth": [
        r"\bELEVATEHEALTH\b"
    ],

    "BIDMC Select": [
        r"\bBIDMC\s*[-–]?\s*SELECT\b"
    ],

    "Local Select": [
        r"\bLOCAL\s+\d+\s+SELECT\b"
    ],

    "BILH": [
        r"\bBILH\b"
    ],

    "Bronze": [
        r"\bBRONZE\b"
    ],

    "Silver": [
        r"\bSILVER\b"
    ],

    "Gold": [
        r"\bGOLD\b"
    ],

    "Platinum": [
        r"\bPLATINUM\b"
    ],
}


# ============================================================
# 6. NORMALIZE TEXT
# ============================================================

def normalize_whitespace(text: str) -> str:

    """
    Normalize Markdown text while preserving tables
    and paragraph structure.
    """

    text = text.replace(
        "\r\n",
        "\n"
    )

    text = text.replace(
        "\r",
        "\n"
    )

    text = text.replace(
        "\t",
        " "
    )

    # Remove trailing spaces
    text = re.sub(
        r"[ \t]+$",
        "",
        text,
        flags=re.MULTILINE
    )

    # Reduce excessive blank lines
    text = re.sub(
        r"\n\s*\n\s*\n+",
        "\n\n",
        text
    )

    return text.strip()


# ============================================================
# 7. INTERNAL DOCUMENT ID EXTRACTION
# ============================================================

def extract_document_id(
    text: str
) -> Optional[str]:

    """
    Extract document ID from inside Markdown.

    Examples:

    ID: MD0000029007_A3

    ID: DN0000000547_A1

    <!-- PageHeader="ID: MD0000028999_A4 X" -->

    Returns:

    MD0000029007_A3
    DN0000000547_A1
    MD0000028999_A4
    """

    patterns = [

        # HTML PageHeader
        (
            r'PageHeader\s*=\s*["\']?'
            r'.*?\bID\s*:\s*'
            r'([A-Z]{2}\d+(?:_[A-Z0-9]+)?)'
        ),

        # Normal ID line
        (
            r'(?im)^\s*[\.\-]?\s*'
            r'ID\s*:\s*'
            r'([A-Z]{2}\d+(?:_[A-Z0-9]+)?)\b'
        ),

        # More permissive fallback
        (
            r'\bID\s*:\s*'
            r'([A-Z]{2}\d+(?:_[A-Z0-9]+)?)\b'
        ),
    ]


    for pattern in patterns:

        match = re.search(
            pattern,
            text,
            flags=re.IGNORECASE
        )

        if match:

            return (
                match.group(1)
                .upper()
                .strip()
            )


    return None


# ============================================================
# 8. EFFECTIVE DATE EXTRACTION
# ============================================================

def extract_effective_date(
    text: str
) -> Optional[str]:

    """
    Examples:

    DATE: 01/01/2020

    EFFECTIVE DATE: 01/01/2026
    """

    patterns = [

        (
            r'(?im)^\s*'
            r'EFFECTIVE\s+DATE\s*:\s*'
            r'(\d{1,2}/\d{1,2}/\d{4})'
        ),

        (
            r'(?im)^\s*'
            r'DATE\s*:\s*'
            r'(\d{1,2}/\d{1,2}/\d{4})'
        ),

        (
            r'\bEFFECTIVE\s+DATE\s*:\s*'
            r'(\d{1,2}/\d{1,2}/\d{4})'
        ),
    ]


    for pattern in patterns:

        match = re.search(
            pattern,
            text,
            flags=re.IGNORECASE
        )

        if match:

            return match.group(1)


    return None


# ============================================================
# 9. FORM NUMBER EXTRACTION
# ============================================================

def extract_form_number(
    text: str
) -> Optional[str]:

    """
    Extract form number only when clearly labelled.

    Examples:

    FORM #1574_16

    FORM NUMBER: ABC123
    """

    patterns = [

        (
            r'(?im)^\s*'
            r'FORM\s*'
            r'(?:NUMBER|NO\.?|#)?'
            r'\s*[:#\-]?\s*'
            r'([A-Z0-9._\-/]{3,})'
        ),
    ]


    for pattern in patterns:

        match = re.search(
            pattern,
            text,
            flags=re.IGNORECASE
        )

        if match:

            return (
                match.group(1)
                .strip()
            )


    return None


# ============================================================
# 10. STATE EXTRACTION
# ============================================================

def extract_state(
    text: str
) -> Optional[str]:

    """
    State generally appears near the top of SOB.
    """

    top_text = (
        text[:6000]
        .upper()
    )


    for state_upper, normalized_state in (
        STATE_PATTERNS.items()
    ):

        if re.search(
            rf"\b{re.escape(state_upper)}\b",
            top_text
        ):

            return normalized_state


    return None


# ============================================================
# 11. REMOVE MARKDOWN MARKUP FROM A LINE
# ============================================================

def remove_markdown_markup(
    line: str
) -> str:

    line = line.strip()

    line = re.sub(
        r"^#{1,6}\s*",
        "",
        line
    )

    line = re.sub(
        r"<!--.*?-->",
        "",
        line
    )

    return line.strip()


# ============================================================
# 12. CLEAN PLAN NAME
# ============================================================

def clean_plan_name(
    plan_name: str
) -> Optional[str]:

    if not plan_name:
        return None


    plan_name = normalize_whitespace(
        plan_name.replace(
            "\n",
            " "
        )
    )


    # Remove trailing state name
    for state in STATE_PATTERNS:

        plan_name = re.sub(
            rf"\b{re.escape(state)}\b\s*$",
            "",
            plan_name,
            flags=re.IGNORECASE
        ).strip()


    return (
        plan_name
        if plan_name
        else None
    )


# ============================================================
# 13. PLAN NAME EXTRACTION
# ============================================================

def extract_plan_name(
    text: str
) -> Optional[str]:

    """
    Extract plan name primarily from opening SOB heading area.
    """

    lines = [

        remove_markdown_markup(
            line
        )

        for line in text.splitlines()
    ]


    lines = [

        line

        for line in lines

        if line
    ]


    useful = []


    for line in lines[:50]:

        upper = line.upper()


        # Skip wrappers
        if upper in {
            "DOCUMENT TEXT",
            "EXTRACTED TABLES",
        }:

            continue


        # Skip ID metadata
        if re.search(
            r"^\s*\.?\s*ID\s*:",
            upper
        ):

            continue


        # Skip dates
        if upper.startswith(
            "DATE:"
        ):

            continue


        if upper.startswith(
            "EFFECTIVE DATE:"
        ):

            continue


        if upper.startswith(
            "FORM "
        ):

            continue


        # Skip page metadata
        if "PAGEHEADER=" in upper:

            continue


        if "PAGEFOOTER=" in upper:

            continue


        if upper == "X":

            continue


        useful.append(
            line
        )


    if not useful:

        return None


    # ========================================================
    # SCHEDULE OF BENEFITS
    # ========================================================

    for index, line in enumerate(
        useful
    ):

        if (
            "SCHEDULE OF BENEFITS"
            not in line.upper()
        ):

            continue


        after = re.sub(
            r"(?i)^.*?"
            r"SCHEDULE\s+OF\s+BENEFITS\s*",
            "",
            line
        ).strip()


        candidates = []


        if after:

            candidates.append(
                after
            )


        for next_line in useful[
            index + 1:index + 7
        ]:

            upper = (
                next_line.upper()
            )


            # Stop at narrative
            stop_phrases = [

                "PLEASE NOTE",

                "IMPORTANT INFORMATION",

                "THIS SCHEDULE",

                "THIS PLAN",

                "SERVICES ARE",

                "COVERAGE UNDER",

                "THE FOLLOWING",

                "YOUR BENEFITS",

                "BENEFITS ARE",
            ]


            if any(
                upper.startswith(
                    phrase
                )
                for phrase
                in stop_phrases
            ):

                break


            candidates.append(
                next_line
            )


        candidate = (
            " ".join(
                candidates
            )
            .strip()
        )


        if candidate:

            return clean_plan_name(
                candidate
            )


    # ========================================================
    # SPECIAL DOCUMENT TYPES
    # ========================================================

    special_pattern = re.compile(
        r"(?i)\b("
        r"PEDIATRIC\s+DENTAL|"
        r"DENTAL\s+RIDER|"
        r"VISIONCARE|"
        r"MEDICARE\s+ENHANCE|"
        r"SENIOR\s+CARE\s+OPTIONS|"
        r"USFHP"
        r")\b"
    )


    for index, line in enumerate(
        useful[:15]
    ):

        if special_pattern.search(
            line
        ):

            candidate = (
                " ".join(
                    useful[
                        index:index + 4
                    ]
                )
            )

            return clean_plan_name(
                candidate
            )


    # Final fallback
    return clean_plan_name(
        useful[0]
    )


# ============================================================
# 14. PRODUCT TYPE EXTRACTION
# ============================================================

def extract_product_type(
    text: str,
    plan_name: Optional[str] = None
) -> str:

    """
    Infer normalized product type.

    Examples:

    BEST BUY HMO 4000 FLEX
        -> HMO

    NATIONAL ACCESS EPO HSA
        -> EPO

    BEST BUY HSA PPO
        -> PPO

    EXPLORER POS
        -> POS
    """

    # Strong preference for opening document information.
    searchable = (
        (plan_name or "")
        + "\n"
        + text[:6000]
    ).upper()


    for (
        product_type,
        patterns
    ) in PRODUCT_PATTERNS:

        for pattern in patterns:

            if re.search(
                pattern,
                searchable,
                flags=re.IGNORECASE
            ):

                return product_type


    return "UNKNOWN"


# ============================================================
# 15. PLAN VARIANT EXTRACTION
# ============================================================

def extract_plan_variants(
    text: str,
    plan_name: Optional[str]
) -> List[str]:

    searchable = (
        (plan_name or "")
        + "\n"
        + text[:4000]
    ).upper()


    found = []


    for (
        variant,
        patterns
    ) in PLAN_VARIANT_PATTERNS.items():

        for pattern in patterns:

            if re.search(
                pattern,
                searchable,
                flags=re.IGNORECASE
            ):

                if variant not in found:

                    found.append(
                        variant
                    )

                break


    # Flex Plus is more specific than Flex
    if (
        "Flex Plus" in found
        and
        "Flex" in found
    ):

        found.remove(
            "Flex"
        )


    return found


# ============================================================
# 16. SPLIT BODY FROM EXTRACTED TABLES
# ============================================================

def split_document_parts(
    text: str
) -> Dict[str, str]:

    """
    Split into:

    document_body
    extracted_tables

    using heading:

    # EXTRACTED TABLES
    """

    pattern = re.compile(
        r"(?im)^#{1,6}\s+"
        r"EXTRACTED\s+TABLES\s*$"
    )


    match = pattern.search(
        text
    )


    if not match:

        return {

            "document_body":
                text.strip(),

            "extracted_tables":
                ""
        }


    return {

        "document_body":
            text[
                :match.start()
            ].strip(),

        "extracted_tables":
            text[
                match.end():
            ].strip()
    }


# ============================================================
# 17. HIERARCHICAL MARKDOWN SECTION PARSER
# ============================================================

def split_into_sections(
    text: str
) -> List[Dict]:

    """
    Split document body by Markdown headings and
    preserve H1-H4 hierarchy.
    """

    lines = text.splitlines()

    sections = []

    hierarchy = {
        1: None,
        2: None,
        3: None,
        4: None,
    }


    current = None


    heading_pattern = re.compile(
        r"^(#{1,6})\s+(.+?)\s*$"
    )


    for line in lines:

        heading = heading_pattern.match(
            line
        )


        if heading:

            level = len(
                heading.group(1)
            )

            title = (
                heading.group(2)
                .strip()
            )


            # Save previous section
            if current:

                section_text = (
                    "\n".join(
                        current["content"]
                    )
                    .strip()
                )


                if section_text:

                    current[
                        "text"
                    ] = section_text

                    del current[
                        "content"
                    ]

                    sections.append(
                        current
                    )


            # Update hierarchy
            if level <= 4:

                hierarchy[
                    level
                ] = title


                # Reset children
                for lower_level in range(
                    level + 1,
                    5
                ):

                    hierarchy[
                        lower_level
                    ] = None


            current = {

                "section":
                    title,

                "level":
                    level,

                "h1":
                    hierarchy[1],

                "h2":
                    hierarchy[2],

                "h3":
                    hierarchy[3],

                "h4":
                    hierarchy[4],

                # Keep heading in chunk text
                "content": [
                    line
                ]
            }


        else:

            if current is None:

                current = {

                    "section":
                        "Document Header",

                    "level":
                        0,

                    "h1":
                        None,

                    "h2":
                        None,

                    "h3":
                        None,

                    "h4":
                        None,

                    "content": []
                }


            current[
                "content"
            ].append(
                line
            )


    # Save final section
    if current:

        section_text = (
            "\n".join(
                current["content"]
            )
            .strip()
        )


        if section_text:

            current[
                "text"
            ] = section_text

            del current[
                "content"
            ]

            sections.append(
                current
            )


    return sections


# ============================================================
# 18. BUILD SECTION PATH
# ============================================================

def build_section_path(
    section: Dict
) -> str:

    parts = []


    for key in [
        "h1",
        "h2",
        "h3",
        "h4",
    ]:

        value = section.get(
            key
        )


        if (
            value
            and
            value not in parts
        ):

            parts.append(
                value
            )


    if not parts:

        section_name = section.get(
            "section"
        )


        if section_name:

            parts.append(
                section_name
            )


    return " > ".join(
        parts
    )


# ============================================================
# 19. HTML TABLE DETECTION
# ============================================================

HTML_TABLE_PATTERN = re.compile(
    r"<table\b[^>]*>.*?</table>",
    flags=(
        re.IGNORECASE
        |
        re.DOTALL
    )
)


# ============================================================
# 20. SPLIT BODY INTO PROSE / HTML TABLE BLOCKS
# ============================================================

def split_html_aware_blocks(
    text: str
) -> List[Dict]:

    """
    HTML table is treated as an atomic block.

    It will not be arbitrarily cut through:

    <table> .... </table>
    """

    blocks = []

    cursor = 0


    for match in (
        HTML_TABLE_PATTERN.finditer(
            text
        )
    ):

        # Text before table
        before = text[
            cursor:match.start()
        ].strip()


        if before:

            blocks.append({

                "type":
                    "prose",

                "text":
                    before
            })


        # Complete HTML table
        blocks.append({

            "type":
                "html_table",

            "text":
                match.group(0)
                .strip()
        })


        cursor = match.end()


    # Remaining content
    after = text[
        cursor:
    ].strip()


    if after:

        blocks.append({

            "type":
                "prose",

            "text":
                after
        })


    return blocks


# ============================================================
# 21. CLEAN OVERLAP
# ============================================================

def get_overlap_text(
    previous_text: str,
    overlap: int
) -> str:

    """
    Return clean overlap without intentionally
    starting in the middle of a paragraph.
    """

    if (
        not previous_text
        or overlap <= 0
    ):

        return ""


    tail = previous_text[
        -overlap:
    ]


    # Prefer paragraph
    position = tail.find(
        "\n\n"
    )


    if position != -1:

        return tail[
            position + 2:
        ].strip()


    # Then line boundary
    position = tail.find(
        "\n"
    )


    if position != -1:

        return tail[
            position + 1:
        ].strip()


    # Then sentence
    position = tail.find(
        ". "
    )


    if position != -1:

        return tail[
            position + 2:
        ].strip()


    return tail.strip()


# ============================================================
# 22. SPLIT LARGE PROSE
# ============================================================

def split_large_prose(
    text: str,
    chunk_size: int = CHUNK_SIZE,
    overlap: int = CHUNK_OVERLAP,
    min_chunk: int = MIN_CHUNK
) -> List[str]:

    """
    Paragraph-aware prose splitting.
    """

    text = text.strip()


    if not text:

        return []


    # Preserve complete short section
    if len(text) <= chunk_size:

        return [
            text
        ]


    paragraphs = re.split(
        r"\n\s*\n",
        text
    )


    chunks = []

    current = ""


    for paragraph in paragraphs:

        paragraph = (
            paragraph.strip()
        )


        if not paragraph:

            continue


        candidate = (
            current
            + "\n\n"
            + paragraph
        ).strip()


        # Fits
        if len(candidate) <= chunk_size:

            current = candidate

            continue


        # Save previous
        if current:

            chunks.append(
                current.strip()
            )


        # ====================================================
        # A single paragraph is too large
        # ====================================================

        if len(paragraph) > chunk_size:

            start = 0


            while start < len(
                paragraph
            ):

                end = min(
                    start + chunk_size,
                    len(paragraph)
                )


                # Try sentence boundary
                if end < len(
                    paragraph
                ):

                    search_start = max(
                        start,
                        end - 800
                    )


                    sentence_end = max(

                        paragraph.rfind(
                            ". ",
                            search_start,
                            end
                        ),

                        paragraph.rfind(
                            ".\n",
                            search_start,
                            end
                        )
                    )


                    if (
                        sentence_end
                        > start
                    ):

                        end = (
                            sentence_end
                            + 1
                        )


                piece = (
                    paragraph[
                        start:end
                    ]
                    .strip()
                )


                if len(piece) >= min_chunk:

                    chunks.append(
                        piece
                    )


                elif piece and chunks:

                    # Merge small residual
                    chunks[-1] = (
                        chunks[-1]
                        + " "
                        + piece
                    )


                if end >= len(
                    paragraph
                ):

                    break


                start = max(
                    end - overlap,
                    start + 1
                )


            current = ""


        else:

            overlap_text = ""


            if chunks:

                overlap_text = (
                    get_overlap_text(
                        chunks[-1],
                        overlap
                    )
                )


            current = (
                overlap_text
                + "\n\n"
                + paragraph
            ).strip()


    # Final chunk
    if current:

        current = current.strip()


        if len(current) >= min_chunk:

            chunks.append(
                current
            )


        elif chunks:

            chunks[-1] = (
                chunks[-1]
                + "\n\n"
                + current
            ).strip()


        else:

            chunks.append(
                current
            )


    return chunks


# ============================================================
# 23. DOCUMENT BODY CHUNKER
# ============================================================

def chunk_document_section(
    section_text: str,
    chunk_size: int = CHUNK_SIZE
) -> List[str]:

    """
    Body chunking:

    - prose handled normally
    - HTML tables preserved
    - HTML tables treated atomically
    - surrounding section context retained when possible
    """

    blocks = split_html_aware_blocks(
        section_text
    )


    if not blocks:

        return []


    chunks = []

    current = ""


    for block in blocks:

        block_type = block[
            "type"
        ]

        block_text = block[
            "text"
        ].strip()


        if not block_text:

            continue


        # ====================================================
        # HTML TABLE
        # ====================================================

        if block_type == "html_table":

            candidate = (
                current
                + "\n\n"
                + block_text
            ).strip()


            # Fits with current context
            if len(candidate) <= chunk_size:

                current = candidate

                continue


            # Save preceding prose
            if current:

                chunks.append(
                    current.strip()
                )

                current = ""


            # IMPORTANT:
            # Preserve HTML table even if larger than target.
            if len(block_text) > chunk_size:

                chunks.append(
                    block_text
                )


            else:

                current = (
                    block_text
                )


        # ====================================================
        # NORMAL PROSE
        # ====================================================

        else:

            if len(block_text) > chunk_size:

                if current:

                    chunks.append(
                        current.strip()
                    )

                    current = ""


                chunks.extend(
                    split_large_prose(
                        block_text
                    )
                )

                continue


            candidate = (
                current
                + "\n\n"
                + block_text
            ).strip()


            if len(candidate) <= chunk_size:

                current = candidate


            else:

                if current:

                    chunks.append(
                        current.strip()
                    )


                overlap_text = ""


                if chunks:

                    # Do not deliberately overlap HTML markup
                    previous = chunks[
                        -1
                    ]


                    if not (
                        "<table" in
                        previous.lower()
                    ):

                        overlap_text = (
                            get_overlap_text(
                                previous,
                                CHUNK_OVERLAP
                            )
                        )


                current = (
                    overlap_text
                    + "\n\n"
                    + block_text
                ).strip()


    if current:

        chunks.append(
            current.strip()
        )


    return [
        chunk

        for chunk in chunks

        if chunk.strip()
    ]


# ============================================================
# 24. SPLIT EXTRACTED TABLE AREA
# ============================================================

def split_extracted_tables(
    extracted_text: str
) -> List[Dict]:

    """
    Expected:

    ## Table 1

    | column | column |
    | --- | --- |
    ...

    ## Table 2
    ...
    """

    if not extracted_text.strip():

        return []


    table_heading_pattern = re.compile(
        r"(?im)^#{1,6}\s+"
        r"(Table\s+\d+[^\n]*)$"
    )


    matches = list(
        table_heading_pattern.finditer(
            extracted_text
        )
    )


    # No explicit Table N headings
    if not matches:

        return [{

            "table_name":
                "Extracted Table",

            "text":
                extracted_text.strip()
        }]


    tables = []


    for index, match in enumerate(
        matches
    ):

        table_name = (
            match.group(1)
            .strip()
        )


        start = match.end()


        if index + 1 < len(
            matches
        ):

            end = (
                matches[
                    index + 1
                ].start()
            )


        else:

            end = len(
                extracted_text
            )


        table_text = (
            extracted_text[
                start:end
            ]
            .strip()
        )


        if table_text:

            tables.append({

                "table_name":
                    table_name,

                "text":
                    table_text
            })


    return tables


# ============================================================
# 25. MARKDOWN TABLE CHUNKER
# ============================================================

def chunk_markdown_table(
    table_text: str,
    table_name: str,
    max_chars: int = TABLE_CHUNK_SIZE
) -> List[str]:

    """
    Markdown table strategy:

    - preserve complete rows
    - repeat table header
    - no character overlap
    """

    lines = [

        line.strip()

        for line in table_text.splitlines()

        if line.strip()
    ]


    table_lines = [

        line

        for line in lines

        if "|" in line
    ]


    # Not recognizable as Markdown table
    if len(table_lines) < 2:

        return [
            table_text.strip()
        ]


    # Normally:
    # Row 1 = column header
    # Row 2 = markdown separator
    header_lines = (
        table_lines[:2]
    )


    data_rows = (
        table_lines[2:]
    )


    header = "\n".join(
        header_lines
    )


    prefix = (
        f"Table: {table_name}"
        + "\n\n"
        + header
    )


    chunks = []

    current_rows = []


    for row in data_rows:

        candidate_rows = (
            current_rows
            + [row]
        )


        candidate = (
            prefix
            + "\n"
            + "\n".join(
                candidate_rows
            )
        )


        if len(candidate) <= max_chars:

            current_rows.append(
                row
            )


        else:

            # Save current rows
            if current_rows:

                chunks.append(
                    (
                        prefix
                        + "\n"
                        + "\n".join(
                            current_rows
                        )
                    ).strip()
                )


            # Start new table chunk
            current_rows = [
                row
            ]


    if current_rows:

        chunks.append(
            (
                prefix
                + "\n"
                + "\n".join(
                    current_rows
                )
            ).strip()
        )


    # Table has only headings
    if not chunks:

        chunks.append(
            prefix.strip()
        )


    return chunks


# ============================================================
# 26. BUILD EMBEDDING TEXT
# ============================================================

def build_embedding_text(
    chunk_text_value: str,
    metadata: Dict
) -> str:

    """
    Add semantic metadata before content.

    Structured metadata remains separately available
    for Azure AI Search filtering.
    """

    parts = []


    if metadata.get(
        "plan_name"
    ):

        parts.append(
            f"Plan: "
            f"{metadata['plan_name']}"
        )


    if (
        metadata.get(
            "product_type"
        )
        and
        metadata[
            "product_type"
        ] != "UNKNOWN"
    ):

        parts.append(
            f"Product Type: "
            f"{metadata['product_type']}"
        )


    if metadata.get(
        "plan_variant"
    ):

        parts.append(
            f"Plan Variant: "
            f"{metadata['plan_variant']}"
        )


    if metadata.get(
        "state"
    ):

        parts.append(
            f"State: "
            f"{metadata['state']}"
        )


    if metadata.get(
        "section_path"
    ):

        parts.append(
            f"Section: "
            f"{metadata['section_path']}"
        )


    if metadata.get(
        "table_name"
    ):

        parts.append(
            f"Table: "
            f"{metadata['table_name']}"
        )


    header = "\n".join(
        parts
    )


    if header:

        return (
            header
            + "\n\n"
            + chunk_text_value
        )


    return chunk_text_value


# ============================================================
# 27. PROCESS ONE MARKDOWN DOCUMENT
# ============================================================

def process_markdown_file(
    file_path: Path
) -> List[Dict]:

    """
    Process one cleaned Markdown file.
    """

    # ========================================================
    # Read
    # ========================================================

    text = file_path.read_text(
        encoding="utf-8",
        errors="ignore"
    )


    text = normalize_whitespace(
        text
    )


    # ========================================================
    # DOCUMENT METADATA
    # ========================================================

    document_id = (
        extract_document_id(
            text
        )
    )


    # Emergency fallback only
    if not document_id:

        print(
            f"WARNING: Internal ID not found: "
            f"{file_path.name}"
        )

        document_id = (
            file_path.stem
        )


    plan_name = (
        extract_plan_name(
            text
        )
    )


    state = (
        extract_state(
            text
        )
    )


    effective_date = (
        extract_effective_date(
            text
        )
    )


    form_number = (
        extract_form_number(
            text
        )
    )


    product_type = (
        extract_product_type(
            text=text,
            plan_name=plan_name
        )
    )


    variants = (
        extract_plan_variants(
            text=text,
            plan_name=plan_name
        )
    )


    plan_variant = (

        " | ".join(
            variants
        )

        if variants

        else None
    )


    # ========================================================
    # SPLIT BODY VS EXTRACTED TABLES
    # ========================================================

    document_parts = (
        split_document_parts(
            text
        )
    )


    document_body = (
        document_parts[
            "document_body"
        ]
    )


    extracted_tables = (
        document_parts[
            "extracted_tables"
        ]
    )


    records = []

    global_chunk_number = 0


    # ========================================================
    # A. DOCUMENT BODY
    # ========================================================

    body_sections = (
        split_into_sections(
            document_body
        )
    )


    for (
        section_index,
        section
    ) in enumerate(
        body_sections,
        start=1
    ):

        section_name = (
            section[
                "section"
            ]
        )


        section_text = (
            section[
                "text"
            ]
        )


        section_path = (
            build_section_path(
                section
            )
        )


        body_chunks = (
            chunk_document_section(
                section_text
            )
        )


        for (
            section_chunk_index,
            chunk
        ) in enumerate(
            body_chunks,
            start=1
        ):

            global_chunk_number += 1


            chunk_id = (
                f"{document_id}"
                f"_chunk_"
                f"{global_chunk_number:04d}"
            )


            metadata = {

                "document_id":
                    document_id,

                "chunk_id":
                    chunk_id,

                "plan_name":
                    plan_name,

                "state":
                    state,

                "effective_date":
                    effective_date,

                "form_number":
                    form_number,

                "product_type":
                    product_type,

                "plan_variant":
                    plan_variant,

                "source_file":
                    file_path.name,

                "section":
                    section_name,

                "section_path":
                    section_path,

                "h1":
                    section.get(
                        "h1"
                    ),

                "h2":
                    section.get(
                        "h2"
                    ),

                "h3":
                    section.get(
                        "h3"
                    ),

                "h4":
                    section.get(
                        "h4"
                    ),

                "section_index":
                    section_index,

                "section_chunk_index":
                    section_chunk_index,

                "chunk_index":
                    global_chunk_number,

                "chunk_type":
                    "text",

                "content_source":
                    "document_body",

                "table_name":
                    None,
            }


            embedding_text = (
                build_embedding_text(
                    chunk_text_value=chunk,
                    metadata=metadata
                )
            )


            record = {

                # Azure AI Search key
                "id":
                    chunk_id,

                **metadata,

                # Original retrieval text
                "text":
                    chunk,

                # Input for embeddings
                "embedding_text":
                    embedding_text,

                "char_count":
                    len(chunk),

                "approx_token_count":
                    round(
                        len(chunk)
                        / 4
                    ),
            }


            records.append(
                record
            )


    # ========================================================
    # B. EXTRACTED MARKDOWN TABLES
    # ========================================================

    tables = (
        split_extracted_tables(
            extracted_tables
        )
    )


    for (
        table_index,
        table
    ) in enumerate(
        tables,
        start=1
    ):

        table_name = (
            table[
                "table_name"
            ]
        )


        table_text = (
            table[
                "text"
            ]
        )


        table_chunks = (
            chunk_markdown_table(
                table_text=table_text,
                table_name=table_name
            )
        )


        for (
            table_chunk_index,
            chunk
        ) in enumerate(
            table_chunks,
            start=1
        ):

            global_chunk_number += 1


            chunk_id = (
                f"{document_id}"
                f"_chunk_"
                f"{global_chunk_number:04d}"
            )


            metadata = {

                "document_id":
                    document_id,

                "chunk_id":
                    chunk_id,

                "plan_name":
                    plan_name,

                "state":
                    state,

                "effective_date":
                    effective_date,

                "form_number":
                    form_number,

                "product_type":
                    product_type,

                "plan_variant":
                    plan_variant,

                "source_file":
                    file_path.name,

                "section":
                    "EXTRACTED TABLES",

                "section_path":
                    (
                        "EXTRACTED TABLES"
                        + " > "
                        + table_name
                    ),

                "h1":
                    "EXTRACTED TABLES",

                "h2":
                    table_name,

                "h3":
                    None,

                "h4":
                    None,

                "section_index":
                    None,

                "section_chunk_index":
                    None,

                "chunk_index":
                    global_chunk_number,

                "chunk_type":
                    "table",

                "content_source":
                    "extracted_table",

                "table_name":
                    table_name,

                "table_index":
                    table_index,

                "table_chunk_index":
                    table_chunk_index,
            }


            embedding_text = (
                build_embedding_text(
                    chunk_text_value=chunk,
                    metadata=metadata
                )
            )


            record = {

                "id":
                    chunk_id,

                **metadata,

                "text":
                    chunk,

                "embedding_text":
                    embedding_text,

                "char_count":
                    len(chunk),

                "approx_token_count":
                    round(
                        len(chunk)
                        / 4
                    ),
            }


            records.append(
                record
            )


    return records


# ============================================================
# 28. PROCESS ALL CLEANED MARKDOWN FILES
# ============================================================

def process_folder(
    input_folder: Path,
    output_file: Path
):

    """
    Process every Markdown file and create one JSONL file.
    """

    md_files = sorted(
        input_folder.rglob(
            "*.md"
        )
    )


    print(
        "=" * 80
    )

    print(
        "POINT32HEALTH SOB CHUNKING PIPELINE"
    )

    print(
        "=" * 80
    )


    print(
        f"\nInput folder:"
    )

    print(
        input_folder
    )


    print(
        f"\nOutput file:"
    )

    print(
        output_file
    )


    print(
        f"\nMarkdown files found: "
        f"{len(md_files)}"
    )


    if not md_files:

        print(
            "\nNo Markdown files found."
        )

        return


    total_documents = 0

    total_chunks = 0

    total_text_chunks = 0

    total_table_chunks = 0

    failed_files = 0


    product_counts = {}

    state_counts = {}


    # ========================================================
    # Write output
    # ========================================================

    with output_file.open(
        "w",
        encoding="utf-8"
    ) as writer:


        for file_path in md_files:

            try:

                records = (
                    process_markdown_file(
                        file_path
                    )
                )


                if not records:

                    print(
                        f"WARNING: No chunks: "
                        f"{file_path.name}"
                    )

                    continue


                # --------------------------------------------
                # Write JSONL
                # --------------------------------------------

                for record in records:

                    writer.write(

                        json.dumps(
                            record,
                            ensure_ascii=False
                        )

                        + "\n"
                    )


                total_documents += 1

                total_chunks += len(
                    records
                )


                text_chunks = sum(

                    1

                    for record in records

                    if (
                        record[
                            "chunk_type"
                        ]
                        ==
                        "text"
                    )
                )


                table_chunks = sum(

                    1

                    for record in records

                    if (
                        record[
                            "chunk_type"
                        ]
                        ==
                        "table"
                    )
                )


                total_text_chunks += (
                    text_chunks
                )

                total_table_chunks += (
                    table_chunks
                )


                # --------------------------------------------
                # Distribution
                # --------------------------------------------

                product = (
                    records[0][
                        "product_type"
                    ]
                )


                state = (
                    records[0].get(
                        "state"
                    )
                    or
                    "UNKNOWN"
                )


                product_counts[
                    product
                ] = (
                    product_counts.get(
                        product,
                        0
                    )
                    + 1
                )


                state_counts[
                    state
                ] = (
                    state_counts.get(
                        state,
                        0
                    )
                    + 1
                )


                # --------------------------------------------
                # File summary
                # --------------------------------------------

                print(
                    f"\nOK: {file_path.name}"
                )

                print(
                    f"    ID           : "
                    f"{records[0]['document_id']}"
                )

                print(
                    f"    Plan         : "
                    f"{records[0]['plan_name']}"
                )

                print(
                    f"    Product Type : "
                    f"{product}"
                )

                print(
                    f"    Variant      : "
                    f"{records[0]['plan_variant']}"
                )

                print(
                    f"    State        : "
                    f"{state}"
                )

                print(
                    f"    Effective    : "
                    f"{records[0]['effective_date']}"
                )

                print(
                    f"    Form         : "
                    f"{records[0]['form_number']}"
                )

                print(
                    f"    Text chunks  : "
                    f"{text_chunks}"
                )

                print(
                    f"    Table chunks : "
                    f"{table_chunks}"
                )

                print(
                    f"    Total chunks : "
                    f"{len(records)}"
                )


            except Exception as error:

                failed_files += 1


                print(
                    f"\nERROR: "
                    f"{file_path.name}"
                )

                print(
                    f"    "
                    f"{type(error).__name__}: "
                    f"{error}"
                )


    # ========================================================
    # FINAL SUMMARY
    # ========================================================

    print(
        "\n" + "=" * 80
    )

    print(
        "CHUNKING COMPLETE"
    )

    print(
        "=" * 80
    )


    print(
        f"Documents processed : "
        f"{total_documents}"
    )

    print(
        f"Files failed        : "
        f"{failed_files}"
    )

    print(
        f"Total chunks        : "
        f"{total_chunks}"
    )

    print(
        f"Text chunks         : "
        f"{total_text_chunks}"
    )

    print(
        f"Table chunks        : "
        f"{total_table_chunks}"
    )


    print(
        "\nPRODUCT TYPE DISTRIBUTION"
    )


    for (
        product,
        count
    ) in sorted(
        product_counts.items(),
        key=lambda item: -item[1]
    ):

        print(
            f"    "
            f"{product:<30} "
            f"{count}"
        )


    print(
        "\nSTATE DISTRIBUTION"
    )


    for (
        state,
        count
    ) in sorted(
        state_counts.items(),
        key=lambda item: -item[1]
    ):

        print(
            f"    "
            f"{state:<30} "
            f"{count}"
        )


    print(
        "\nJSONL saved to:"
    )

    print(
        output_file
    )


# ============================================================
# 29. RUN
# ============================================================

if __name__ == "__main__":

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )


    process_folder(
        INPUT_FOLDER,
        OUTPUT_FILE
    )