# -*- coding: utf-8 -*-
"""chunking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LzpUtZQAehwCPMGQqopg_hR1Ti9f057C
"""

import re
import json
from pathlib import Path
from datetime import datetime


# ============================================================
# 1. CONFIGURATION
# ============================================================

BASE_DIR = Path(
    r"C:\Users\mm7453\OneDrive - Point32Health\p32_workplace\adhoc\SOBs"
)

SOURCE_DIR = BASE_DIR / "cleaned_md_files"

OUTPUT_DIR = BASE_DIR / "chunked_files"

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

OUTPUT_JSONL = OUTPUT_DIR / "sob_chunks.jsonl"


# ------------------------------------------------------------
# Chunk sizes
#
# Rough assumption:
# 1 token ~= 4 characters
#
# 3200 chars ~= approximately 700-900 tokens
# 400 chars overlap ~= approximately 100 tokens
# ------------------------------------------------------------

MAX_CHARS = 3200

OVERLAP_CHARS = 400

MIN_CHUNK_CHARS = 100


# ============================================================
# 2. NORMALIZE TEXT
# ============================================================

def normalize_text(text):
    """
    Basic text normalization without destroying Markdown structure.
    """

    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    # Remove trailing spaces
    text = re.sub(
        r"[ \t]+$",
        "",
        text,
        flags=re.MULTILINE
    )

    # Reduce excessive blank lines
    text = re.sub(
        r"\n\s*\n\s*\n+",
        "\n\n",
        text
    )

    return text.strip()


# ============================================================
# 3. DOCUMENT ID
# ============================================================

def get_document_id(file_path):
    """
    Example:

    DN0000000113.md
            ↓
    DN0000000113
    """

    return file_path.stem


# ============================================================
# 4. EXTRACT METADATA FROM DOCUMENT
# ============================================================

def extract_document_metadata(text, file_path):
    """
    Extract useful metadata from SOB documents.

    Attempts to find:
    - document_id
    - plan_name
    - state
    - effective_date
    - form_number
    - page header ID

    Missing information is stored as None.
    """

    metadata = {
        "document_id": get_document_id(file_path),
        "source_file": file_path.name,
        "plan_name": None,
        "state": None,
        "effective_date": None,
        "form_number": None,
        "page_header_id": None,
    }

    # --------------------------------------------------------
    # Page Header
    #
    # Example:
    # <!-- PageHeader="ID: MD0000003920_AE2 X" -->
    # --------------------------------------------------------

    match = re.search(
        r'PageHeader\s*=\s*"([^"]+)"',
        text,
        flags=re.IGNORECASE
    )

    if match:
        metadata["page_header_id"] = match.group(1).strip()


    # --------------------------------------------------------
    # Effective Date
    #
    # Example:
    # EFFECTIVE DATE: 01/01/2026
    # --------------------------------------------------------

    match = re.search(
        r"EFFECTIVE\s+DATE\s*:\s*"
        r"(\d{1,2}/\d{1,2}/\d{4})",
        text,
        flags=re.IGNORECASE
    )

    if match:
        metadata["effective_date"] = match.group(1)


    # --------------------------------------------------------
    # Form Number
    #
    # Example:
    # FORM #1574_16
    # --------------------------------------------------------

    match = re.search(
        r"FORM\s*#?\s*([A-Za-z0-9_\-]+)",
        text,
        flags=re.IGNORECASE
    )

    if match:
        metadata["form_number"] = match.group(1).strip()


    # --------------------------------------------------------
    # Try to infer plan name and state from front matter
    # --------------------------------------------------------

    first_lines = []

    for line in text.splitlines()[:50]:

        clean_line = line.strip()

        if not clean_line:
            continue

        if clean_line.startswith("<!--"):
            continue

        if clean_line.startswith("#"):
            continue

        first_lines.append(clean_line)


    # --------------------------------------------------------
    # Typical plan names
    # --------------------------------------------------------

    plan_keywords = [
        "HMO",
        "PPO",
        "LP",
        "POS",
        "EPO",
    ]

    for line in first_lines:

        upper_line = line.upper()

        if any(
            keyword in upper_line
            for keyword in plan_keywords
        ):

            # Avoid very long paragraphs
            if len(line) < 150:

                metadata["plan_name"] = line

                break


    # --------------------------------------------------------
    # State detection
    # --------------------------------------------------------

    states = [
        "MAINE",
        "MASSACHUSETTS",
        "NEW HAMPSHIRE",
        "RHODE ISLAND",
        "CONNECTICUT",
    ]

    for line in first_lines:

        normalized = line.upper().strip()

        for state in states:

            if normalized == state:

                metadata["state"] = state.title()

                break

        if metadata["state"]:
            break


    return metadata


# ============================================================
# 5. HEADING DETECTION
# ============================================================

def parse_heading(line):
    """
    Detect Markdown headings.

    Returns:
        heading_level
        heading_text

    Example:
        ## Covered Benefits

    returns:
        2, "Covered Benefits"
    """

    match = re.match(
        r"^(#{1,6})\s+(.+?)\s*$",
        line
    )

    if not match:
        return None

    level = len(
        match.group(1)
    )

    title = match.group(2).strip()

    return level, title


# ============================================================
# 6. PARSE DOCUMENT INTO SECTIONS
# ============================================================

def parse_markdown_sections(text):
    """
    Parse Markdown while preserving H1-H4 hierarchy.

    Each returned section contains:

    {
        h1:
        h2:
        h3:
        h4:
        title:
        level:
        content:
    }
    """

    sections = []

    hierarchy = {
        1: None,
        2: None,
        3: None,
        4: None
    }

    current_section = None

    lines = text.splitlines()

    for line in lines:

        heading = parse_heading(line)

        if heading:

            level, title = heading

            # ------------------------------------------------
            # Save previous section
            # ------------------------------------------------

            if current_section:

                content = "\n".join(
                    current_section["content"]
                ).strip()

                if content:

                    current_section["content"] = content

                    sections.append(
                        current_section
                    )


            # ------------------------------------------------
            # Update hierarchy
            # ------------------------------------------------

            if level <= 4:

                hierarchy[level] = title

                # Clear lower hierarchy levels
                for lower_level in range(
                    level + 1,
                    5
                ):

                    hierarchy[lower_level] = None


            current_section = {
                "level": level,
                "title": title,
                "h1": hierarchy[1],
                "h2": hierarchy[2],
                "h3": hierarchy[3],
                "h4": hierarchy[4],
                "content": []
            }

        else:

            # ------------------------------------------------
            # Text before first heading
            # ------------------------------------------------

            if current_section is None:

                current_section = {
                    "level": 0,
                    "title": "Front Matter",
                    "h1": None,
                    "h2": None,
                    "h3": None,
                    "h4": None,
                    "content": []
                }

            current_section["content"].append(
                line
            )


    # --------------------------------------------------------
    # Save final section
    # --------------------------------------------------------

    if current_section:

        content = "\n".join(
            current_section["content"]
        ).strip()

        if content:

            current_section["content"] = content

            sections.append(
                current_section
            )


    return sections


# ============================================================
# 7. BUILD SECTION PATH
# ============================================================

def build_section_path(section):
    """
    Example:

    DOCUMENT TEXT
        >
    Covered Benefits
        >
    Durable Medical Equipment
    """

    parts = []

    for key in [
        "h1",
        "h2",
        "h3",
        "h4"
    ]:

        value = section.get(key)

        if (
            value
            and value not in parts
        ):

            parts.append(value)

    if not parts:

        parts.append(
            section.get(
                "title",
                "Front Matter"
            )
        )

    return " > ".join(parts)


# ============================================================
# 8. CHECK IF SECTION IS TABLE
# ============================================================

def is_table_section(section):
    """
    Identify extracted table sections.
    """

    values = [
        section.get("h1"),
        section.get("h2"),
        section.get("h3"),
        section.get("h4"),
        section.get("title"),
    ]

    values = [
        value.lower()
        for value in values
        if value
    ]

    # Extracted tables
    if any(
        "extracted tables" in value
        for value in values
    ):
        return True

    # Table 1, Table 2 etc.
    if any(
        re.search(
            r"\btable\s+\d+",
            value,
            flags=re.IGNORECASE
        )
        for value in values
    ):
        return True

    return False


# ============================================================
# 9. SPLIT TEXT AT PARAGRAPH BOUNDARIES
# ============================================================

def split_text_section(
    text,
    max_chars=MAX_CHARS,
    overlap_chars=OVERLAP_CHARS
):
    """
    Split large text sections while attempting to preserve
    paragraph boundaries.

    Small sections remain as one chunk.
    """

    text = text.strip()

    if len(text) <= max_chars:

        return [text]


    paragraphs = re.split(
        r"\n\s*\n",
        text
    )

    chunks = []

    current_chunk = ""


    for paragraph in paragraphs:

        paragraph = paragraph.strip()

        if not paragraph:
            continue


        # ----------------------------------------------------
        # Paragraph itself is too large
        # ----------------------------------------------------

        if len(paragraph) > max_chars:

            # Save existing chunk
            if current_chunk:

                chunks.append(
                    current_chunk.strip()
                )

                current_chunk = ""


            start = 0

            while start < len(paragraph):

                end = start + max_chars

                piece = paragraph[
                    start:end
                ].strip()

                if piece:

                    chunks.append(piece)

                start = (
                    end - overlap_chars
                )

            continue


        # ----------------------------------------------------
        # Try adding paragraph to current chunk
        # ----------------------------------------------------

        candidate = (
            current_chunk
            + "\n\n"
            + paragraph
        ).strip()


        if len(candidate) <= max_chars:

            current_chunk = candidate

        else:

            if current_chunk:

                chunks.append(
                    current_chunk.strip()
                )


            # -----------------------------------------------
            # Add overlap from previous chunk
            # -----------------------------------------------

            overlap = ""

            if chunks and overlap_chars > 0:

                previous = chunks[-1]

                overlap = previous[
                    -overlap_chars:
                ]

                # Try beginning overlap at word boundary
                first_space = overlap.find(" ")

                if first_space != -1:

                    overlap = overlap[
                        first_space + 1:
                    ]


            current_chunk = (
                overlap
                + "\n\n"
                + paragraph
            ).strip()


    if current_chunk:

        chunks.append(
            current_chunk.strip()
        )


    return chunks


# ============================================================
# 10. SPLIT MARKDOWN TABLES
# ============================================================

def split_table_section(
    text,
    max_chars=MAX_CHARS
):
    """
    Preserve small tables.

    For large Markdown tables:
    - preserve table header
    - split rows into smaller chunks
    """

    text = text.strip()

    if len(text) <= max_chars:

        return [text]


    lines = [
        line
        for line in text.splitlines()
        if line.strip()
    ]


    # --------------------------------------------------------
    # If it does not look like a Markdown table,
    # fall back to normal splitting
    # --------------------------------------------------------

    table_lines = [
        line
        for line in lines
        if "|" in line
    ]

    if len(table_lines) < 2:

        return split_text_section(
            text,
            max_chars=max_chars,
            overlap_chars=0
        )


    # --------------------------------------------------------
    # Assume first two table lines are:
    #
    # header
    # separator
    # --------------------------------------------------------

    header_lines = table_lines[:2]

    data_lines = table_lines[2:]


    header = "\n".join(
        header_lines
    )


    chunks = []

    current_rows = []


    for row in data_lines:

        candidate_rows = (
            current_rows
            + [row]
        )

        candidate = (
            header
            + "\n"
            + "\n".join(
                candidate_rows
            )
        )


        if len(candidate) <= max_chars:

            current_rows.append(row)

        else:

            if current_rows:

                chunks.append(
                    header
                    + "\n"
                    + "\n".join(
                        current_rows
                    )
                )

            current_rows = [row]


    if current_rows:

        chunks.append(
            header
            + "\n"
            + "\n".join(
                current_rows
            )
        )


    return chunks


# ============================================================
# 11. CREATE EMBEDDING TEXT
# ============================================================

def create_embedding_text(
    section_path,
    chunk_text,
    metadata
):
    """
    Add meaningful document context before the chunk.

    This is useful when generating embeddings later.
    """

    context = []

    if metadata.get("plan_name"):

        context.append(
            f"Plan: {metadata['plan_name']}"
        )

    if metadata.get("state"):

        context.append(
            f"State: {metadata['state']}"
        )

    if metadata.get("effective_date"):

        context.append(
            f"Effective Date: {metadata['effective_date']}"
        )

    if section_path:

        context.append(
            f"Section: {section_path}"
        )


    context_text = "\n".join(
        context
    )


    if context_text:

        return (
            context_text
            + "\n\n"
            + chunk_text
        )


    return chunk_text


# ============================================================
# 12. CHUNK ONE DOCUMENT
# ============================================================

def chunk_document(file_path):
    """
    Parse and chunk one Markdown document.
    """

    text = file_path.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    text = normalize_text(text)

    document_metadata = (
        extract_document_metadata(
            text,
            file_path
        )
    )

    sections = parse_markdown_sections(
        text
    )


    chunks = []

    chunk_index = 0


    for section in sections:

        content = section[
            "content"
        ].strip()

        if len(content) < MIN_CHUNK_CHARS:
            continue


        section_path = build_section_path(
            section
        )


        # ----------------------------------------------------
        # TABLE
        # ----------------------------------------------------

        if is_table_section(section):

            chunk_type = "table"

            section_chunks = (
                split_table_section(
                    content
                )
            )


        # ----------------------------------------------------
        # NORMAL TEXT
        # ----------------------------------------------------

        else:

            chunk_type = "text"

            section_chunks = (
                split_text_section(
                    content
                )
            )


        # ----------------------------------------------------
        # Create individual chunk records
        # ----------------------------------------------------

        for part_index, chunk_text in enumerate(
            section_chunks,
            start=1
        ):

            if (
                len(chunk_text.strip())
                < MIN_CHUNK_CHARS
            ):
                continue


            chunk_index += 1


            chunk_id = (
                f"{document_metadata['document_id']}"
                f"_chunk_{chunk_index:04d}"
            )


            embedding_text = (
                create_embedding_text(
                    section_path,
                    chunk_text,
                    document_metadata
                )
            )


            chunk_record = {

                # -------------------------------------------
                # Unique identifiers
                # -------------------------------------------

                "chunk_id": chunk_id,

                "document_id":
                    document_metadata[
                        "document_id"
                    ],

                "source_file":
                    document_metadata[
                        "source_file"
                    ],


                # -------------------------------------------
                # Chunk information
                # -------------------------------------------

                "chunk_index": chunk_index,

                "section_chunk_index":
                    part_index,

                "chunk_type":
                    chunk_type,


                # -------------------------------------------
                # Document hierarchy
                # -------------------------------------------

                "h1":
                    section.get("h1"),

                "h2":
                    section.get("h2"),

                "h3":
                    section.get("h3"),

                "h4":
                    section.get("h4"),

                "section_title":
                    section.get("title"),

                "section_path":
                    section_path,


                # -------------------------------------------
                # Document metadata
                # -------------------------------------------

                "plan_name":
                    document_metadata.get(
                        "plan_name"
                    ),

                "state":
                    document_metadata.get(
                        "state"
                    ),

                "effective_date":
                    document_metadata.get(
                        "effective_date"
                    ),

                "form_number":
                    document_metadata.get(
                        "form_number"
                    ),

                "page_header_id":
                    document_metadata.get(
                        "page_header_id"
                    ),


                # -------------------------------------------
                # Text
                # -------------------------------------------

                "text":
                    chunk_text,

                "embedding_text":
                    embedding_text,


                # -------------------------------------------
                # Statistics
                # -------------------------------------------

                "char_count":
                    len(chunk_text),

                "approx_token_count":
                    round(
                        len(chunk_text) / 4
                    )
            }


            chunks.append(
                chunk_record
            )


    return chunks


# ============================================================
# 13. PROCESS ALL MARKDOWN FILES
# ============================================================

def process_all_files():

    md_files = sorted(
        SOURCE_DIR.glob("*.md")
    )


    print(
        "=" * 75
    )

    print(
        "POINT32HEALTH SOB CHUNKING PIPELINE"
    )

    print(
        "=" * 75
    )

    print(
        f"\nSource:"
    )

    print(
        SOURCE_DIR
    )

    print(
        f"\nOutput:"
    )

    print(
        OUTPUT_JSONL
    )

    print(
        f"\nMarkdown files found: "
        f"{len(md_files)}"
    )


    if not md_files:

        print(
            "\nNo Markdown files found."
        )

        return


    total_chunks = 0

    successful_files = 0

    failed_files = 0


    # --------------------------------------------------------
    # Open JSONL once and append every document's chunks
    # --------------------------------------------------------

    with OUTPUT_JSONL.open(
        "w",
        encoding="utf-8"
    ) as output_file:


        for file_path in md_files:

            try:

                print(
                    "\n" + "-" * 75
                )

                print(
                    f"Processing: "
                    f"{file_path.name}"
                )


                chunks = chunk_document(
                    file_path
                )


                for chunk in chunks:

                    output_file.write(
                        json.dumps(
                            chunk,
                            ensure_ascii=False
                        )
                        + "\n"
                    )


                print(
                    f"Created "
                    f"{len(chunks)} chunks"
                )


                text_chunks = sum(
                    1
                    for chunk in chunks
                    if chunk[
                        "chunk_type"
                    ] == "text"
                )


                table_chunks = sum(
                    1
                    for chunk in chunks
                    if chunk[
                        "chunk_type"
                    ] == "table"
                )


                print(
                    f"    Text chunks  : "
                    f"{text_chunks}"
                )

                print(
                    f"    Table chunks : "
                    f"{table_chunks}"
                )


                total_chunks += len(
                    chunks
                )

                successful_files += 1


            except Exception as e:

                failed_files += 1

                print(
                    f"ERROR processing "
                    f"{file_path.name}"
                )

                print(
                    f"{type(e).__name__}: {e}"
                )


    # ========================================================
    # FINAL SUMMARY
    # ========================================================

    print(
        "\n" + "=" * 75
    )

    print(
        "CHUNKING COMPLETE"
    )

    print(
        "=" * 75
    )


    print(
        f"Files processed successfully : "
        f"{successful_files}"
    )

    print(
        f"Files failed                 : "
        f"{failed_files}"
    )

    print(
        f"Total chunks created         : "
        f"{total_chunks}"
    )

    print(
        "\nJSONL saved to:"
    )

    print(
        OUTPUT_JSONL
    )


# ============================================================
# 14. ENTRY POINT
# ============================================================

if __name__ == "__main__":

    process_all_files()