# -*- coding: utf-8 -*-
"""CHUNKING11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rHV82GSeKUTV44gFMaWG2e3T4P7gnMry
"""

# ============================================================
# SOB MARKDOWN -> RAG CHUNKS JSONL
#
# Extracts:
#   - document_id from ID inside .md
#   - chunk_id
#   - plan_name
#   - state
#   - effective_date
#   - form_number
#   - product_type
#   - plan_variant
#   - source_file
#   - section
#   - text
#   - embedding_text
#
# Output:
#   sob_chunks.jsonl
# ============================================================

from pathlib import Path
import re
import json
from typing import Optional, Dict, List


# ============================================================
# 1. CONFIGURATION
# ============================================================

INPUT_FOLDER = Path("/path/to/your/md/files")
OUTPUT_FILE = Path("/path/to/output/sob_chunks.jsonl")

CHUNK_SIZE = 1800
CHUNK_OVERLAP = 250


# ============================================================
# 2. STATES
# ============================================================

STATE_PATTERNS = {
    "MASSACHUSETTS": "Massachusetts",
    "MAINE": "Maine",
    "NEW HAMPSHIRE": "New Hampshire",
    "RHODE ISLAND": "Rhode Island",
    "CONNECTICUT": "Connecticut",
    "VERMONT": "Vermont",
    "NEW YORK": "New York",
}


# ============================================================
# 3. PRODUCT TYPE RULES
#
# Order is important.
# More-specific patterns should appear before generic patterns.
# ============================================================

PRODUCT_PATTERNS = [

    # --------------------------------------------------------
    # Dental
    # --------------------------------------------------------
    (
        "Pediatric Dental",
        [
            r"\bPEDIATRIC\s+DENTAL\s+RIDER\b",
            r"\bPEDIATRIC\s+DENTAL\b",
        ]
    ),

    (
        "Dental",
        [
            r"\bDENTAL\s+RIDER\b",
            r"\bPREVENTIVE\s+DENTAL\b",
            r"\bDENTAL\s+PLAN\b",
        ]
    ),

    # --------------------------------------------------------
    # Vision
    # --------------------------------------------------------
    (
        "Vision",
        [
            r"\bVISIONCARE\b",
            r"\bVISION\s+CARE\b",
            r"\bVISION\s+BENEFIT\b",
        ]
    ),

    # --------------------------------------------------------
    # Medicare
    # --------------------------------------------------------
    (
        "Medicare Enhance",
        [
            r"\bMEDICARE\s+ENHANCE\b",
        ]
    ),

    (
        "Medicare Advantage PPO",
        [
            r"\bMEDICARE\s+PREFERRED\s+PPO\b",
            r"\bMEDICARE\s+ADVANTAGE\s+PPO\b",
        ]
    ),

    (
        "Medicare Advantage HMO",
        [
            r"\bMEDICARE\s+PREFERRED\s+HMO\b",
            r"\bMEDICARE\s+ADVANTAGE\s+HMO\b",
        ]
    ),

    (
        "Medicare",
        [
            r"\bMEDICARE\b",
        ]
    ),

    # --------------------------------------------------------
    # Special government / dual products
    # --------------------------------------------------------
    (
        "USFHP",
        [
            r"\bUSFHP\b",
            r"\bUNIFORMED\s+SERVICES\s+FAMILY\s+HEALTH\s+PLAN\b",
        ]
    ),

    (
        "D-SNP",
        [
            r"\bD[\s-]?SNP\b",
            r"\bDUAL\s+ELIGIBLE\s+SPECIAL\s+NEEDS\b",
        ]
    ),

    (
        "SCO",
        [
            r"\bSENIOR\s+CARE\s+OPTIONS\b",
            r"\bSCO\b",
        ]
    ),

    # --------------------------------------------------------
    # Main commercial medical product types
    # --------------------------------------------------------
    (
        "EPO",
        [
            r"\bEPO\b",
        ]
    ),

    (
        "PPO",
        [
            r"\bPPO\b",
        ]
    ),

    (
        "POS",
        [
            r"\bPOS\b",
            r"\bPOINT[\s-]+OF[\s-]+SERVICE\b",
        ]
    ),

    (
        "DPO",
        [
            r"\bDPO\b",
        ]
    ),

    (
        "GEO",
        [
            r"\bGEO\b",
        ]
    ),

    (
        "HMO",
        [
            r"\bHMO\b",
        ]
    ),
]


# ============================================================
# 4. PLAN VARIANTS
#
# These are NOT treated as the main product_type.
#
# Example:
#   NATIONAL ACCESS EPO HSA
#
# product_type = EPO
# plan_variant = National Access | HSA
# ============================================================

PLAN_VARIANT_PATTERNS = {

    "HSA": [
        r"\bHSA\b"
    ],

    "CDHP": [
        r"\bCDHP\b"
    ],

    "Flex": [
        r"\bFLEX\b"
    ],

    "Flex Plus": [
        r"\bFLEX\s+PLUS\b"
    ],

    "ChoiceNet": [
        r"\bCHOICENET\b"
    ],

    "Choice Plus": [
        r"\bCHOICE\s+PLUS\b"
    ],

    "National Access": [
        r"\bNATIONAL\s+ACCESS\b"
    ],

    "Tiered": [
        r"\bTIERED\b"
    ],

    "Quality": [
        r"\bQUALITY\b"
    ],

    "Focus Network": [
        r"\bFOCUS\s+NETWORK\b"
    ],

    "Network Premier": [
        r"\bNETWORK\s+PREMIER\b"
    ],

    "Domestic and Community": [
        r"\bDOMESTIC\s+AND\s+COMMUNITY\b"
    ],

    "Out of Area": [
        r"\bOUT\s+OF\s+AREA\b"
    ],

    "Explorer": [
        r"\bEXPLORER\b"
    ],

    "Best Buy": [
        r"\bBEST\s+BUY\b"
    ],

    "Maine's Choice Plus": [
        r"\bMAINE['’]S\s+CHOICE\s+PLUS\b"
    ],

    "Littleton Options": [
        r"\bLITTLETON\s+OPTIONS\b"
    ],

    "myClassic": [
        r"\bMYCLASSIC\b"
    ],

    "myAdvantage": [
        r"\bMYADVANTAGE\b"
    ],

    "ElevateHealth": [
        r"\bELEVATEHEALTH\b"
    ],

    "BIDMC Select": [
        r"\bBIDMC\s*[-–]?\s*SELECT\b"
    ],

    "Local Select": [
        r"\bLOCAL\s+\d+\s+SELECT\b"
    ],
}


# ============================================================
# 5. TEXT CLEANUP
# ============================================================

def normalize_whitespace(text: str) -> str:
    """
    Keep paragraph structure but clean excessive spaces/newlines.
    """

    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    # Tabs -> spaces
    text = text.replace("\t", " ")

    # Multiple spaces
    text = re.sub(r"[ ]{2,}", " ", text)

    # More than 2 blank lines -> 2
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


# ============================================================
# 6. DOCUMENT ID EXTRACTION
# ============================================================

def extract_document_id(text: str) -> Optional[str]:
    """
    Extract ID from the markdown itself.

    Supported examples:

    <!-- PageHeader="ID: MD0000028999_A4 X" -->

    ID: MD0000029007_A3
    X

    ID: DN0000000547_A1
    DATE: 01/01/2020

    <!-- PageHeader="ID: MD00000201951" -->

    Extra trailing standalone X is removed automatically.
    """

    patterns = [

        # HTML PageHeader
        r'PageHeader\s*=\s*["\']?\s*ID\s*:\s*([A-Z]{2}\d+(?:_[A-Z0-9]+)?)',

        # Normal ID line
        r'(?im)^\s*[\.\-]?\s*ID\s*:\s*([A-Z]{2}\d+(?:_[A-Z0-9]+)?)\b',

        # More permissive fallback
        r'\bID\s*:\s*([A-Z]{2}\d+(?:_[A-Z0-9]+)?)\b',
    ]

    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE)

        if match:
            return match.group(1).upper().strip()

    return None


# ============================================================
# 7. EFFECTIVE DATE
# ============================================================

def extract_effective_date(text: str) -> Optional[str]:
    """
    Examples:
        DATE: 01/01/2020
        DATE: 07/01/2012
    """

    patterns = [
        r'(?im)^\s*DATE\s*:\s*(\d{1,2}/\d{1,2}/\d{4})',
        r'\bDATE\s*:\s*(\d{1,2}/\d{1,2}/\d{4})',
    ]

    for pattern in patterns:

        match = re.search(pattern, text)

        if match:
            return match.group(1)

    return None


# ============================================================
# 8. FORM NUMBER
# ============================================================

def extract_form_number(text: str) -> Optional[str]:
    """
    Extract form numbers only where there is a clear label.

    We intentionally do NOT assume document_id == form_number.
    """

    patterns = [

        r'(?im)^\s*FORM\s*(?:NUMBER|NO\.?|#)?\s*[:\-]\s*([A-Z0-9._\-/]+)',

        r'(?im)^\s*FORM\s+([A-Z0-9._\-/]{4,})\s*$',
    ]

    for pattern in patterns:

        match = re.search(pattern, text)

        if match:
            return match.group(1).strip()

    return None


# ============================================================
# 9. STATE EXTRACTION
# ============================================================

def extract_state(text: str) -> Optional[str]:
    """
    Look primarily near the top because state is normally
    part of the Schedule of Benefits heading.
    """

    top_text = text[:5000].upper()

    for state_upper, normalized_state in STATE_PATTERNS.items():

        if re.search(
            rf"\b{re.escape(state_upper)}\b",
            top_text
        ):
            return normalized_state

    return None


# ============================================================
# 10. PLAN TITLE / PLAN NAME
# ============================================================

def remove_markdown_markup(line: str) -> str:

    line = line.strip()

    # Markdown heading
    line = re.sub(r"^#+\s*", "", line)

    # HTML comment
    line = re.sub(
        r"<!--.*?-->",
        "",
        line
    )

    return line.strip()


def extract_plan_name(text: str) -> Optional[str]:
    """
    Extract the plan name from the opening section.

    Typical examples:

    Schedule of Benefits
    Harvard Pilgrim Health Care, Inc.
    BEST BUY HMO 4000 - FLEX
    MASSACHUSETTS

    or:

    # Schedule of Benefits Harvard Pilgrim Health Care, Inc.
      NATIONAL ACCESS EPO HSA MASSACHUSETTS

    or:

    Pediatric Dental Rider - HMO
    Harvard Pilgrim Health Care, Inc.
    MAINE
    """

    lines = [
        remove_markdown_markup(x)
        for x in text.splitlines()
    ]

    lines = [
        x for x in lines
        if x
    ]

    # Remove known metadata/header lines
    useful = []

    for line in lines[:30]:

        upper = line.upper()

        if upper == "DOCUMENT TEXT":
            continue

        if upper.startswith("ID:"):
            continue

        if upper.startswith(".ID:"):
            continue

        if upper.startswith("DATE:"):
            continue

        if "PAGEHEADER=" in upper:
            continue

        if upper == "X":
            continue

        useful.append(line)

    if not useful:
        return None

    # --------------------------------------------------------
    # Find Schedule of Benefits
    # --------------------------------------------------------

    for i, line in enumerate(useful):

        upper = line.upper()

        if "SCHEDULE OF BENEFITS" in upper:

            after = re.sub(
                r"(?i)^SCHEDULE\s+OF\s+BENEFITS\s*",
                "",
                line
            ).strip()

            candidate_lines = []

            if after:
                candidate_lines.append(after)

            # Capture following title lines.
            for nxt in useful[i + 1:i + 6]:

                nxt_upper = nxt.upper()

                # Stop when actual narrative begins
                if any([
                    nxt_upper.startswith("PLEASE NOTE"),
                    nxt_upper.startswith("IMPORTANT INFORMATION"),
                    nxt_upper.startswith("THIS SCHEDULE"),
                    nxt_upper.startswith("THIS PLAN"),
                    nxt_upper.startswith("SERVICES ARE"),
                    nxt_upper.startswith("COVERAGE UNDER"),
                    nxt_upper.startswith("THE PEDIATRIC"),
                ]):
                    break

                candidate_lines.append(nxt)

            candidate = " ".join(candidate_lines).strip()

            if candidate:
                return clean_plan_name(candidate)

    # --------------------------------------------------------
    # Dental / Vision can sometimes not have SOB
    # --------------------------------------------------------

    for i, line in enumerate(useful[:10]):

        if re.search(
            r"(?i)\b("
            r"PEDIATRIC\s+DENTAL|"
            r"DENTAL\s+RIDER|"
            r"VISIONCARE|"
            r"MEDICARE\s+ENHANCE"
            r")\b",
            line
        ):

            candidate = " ".join(
                useful[i:i + 4]
            )

            return clean_plan_name(candidate)

    return clean_plan_name(useful[0])


def clean_plan_name(plan_name: str) -> str:
    """
    Removes state name from end of plan title while
    retaining useful insurer/product name.
    """

    plan_name = normalize_whitespace(
        plan_name.replace("\n", " ")
    )

    # Remove state words at end
    for state in STATE_PATTERNS:

        plan_name = re.sub(
            rf"\b{re.escape(state)}\b\s*$",
            "",
            plan_name,
            flags=re.IGNORECASE
        ).strip()

    return plan_name or None


# ============================================================
# 11. PRODUCT TYPE
# ============================================================

def extract_product_type(
    text: str,
    plan_name: Optional[str] = None
) -> str:
    """
    Product type is primarily inferred from plan title.

    Examples:

    BEST BUY HMO 4000 - FLEX
        -> HMO

    NATIONAL ACCESS EPO HSA
        -> EPO

    BEST BUY HSA PPO
        -> PPO

    Explorer POS
        -> POS

    Pediatric Dental Rider - HMO
        -> Pediatric Dental

    VisionCare
        -> Vision
    """

    searchable = (
        (plan_name or "") +
        "\n" +
        text[:5000]
    ).upper()

    for product_type, patterns in PRODUCT_PATTERNS:

        for pattern in patterns:

            if re.search(
                pattern,
                searchable,
                flags=re.IGNORECASE
            ):
                return product_type

    return "UNKNOWN"


# ============================================================
# 12. PLAN VARIANT EXTRACTION
# ============================================================

def extract_plan_variants(
    text: str,
    plan_name: Optional[str]
) -> List[str]:

    searchable = (
        (plan_name or "") +
        "\n" +
        text[:3000]
    ).upper()

    found = []

    # Check more specific variants first
    ordered_items = sorted(
        PLAN_VARIANT_PATTERNS.items(),
        key=lambda x: max(len(p) for p in x[1]),
        reverse=True
    )

    for variant, patterns in ordered_items:

        for pattern in patterns:

            if re.search(
                pattern,
                searchable,
                flags=re.IGNORECASE
            ):

                if variant not in found:
                    found.append(variant)

                break

    # Avoid duplicate semantics
    if "Flex Plus" in found and "Flex" in found:
        found.remove("Flex")

    return found


# ============================================================
# 13. SECTION DETECTION
# ============================================================

def split_into_sections(text: str) -> List[Dict]:
    """
    Split using markdown headings.

    Keeps each section title with its content.
    """

    heading_pattern = re.compile(
        r"(?m)^(#{1,6})\s+(.+?)\s*$"
    )

    matches = list(
        heading_pattern.finditer(text)
    )

    if not matches:

        return [{
            "section": "Document",
            "text": text.strip()
        }]

    sections = []

    # Text before first heading
    if matches[0].start() > 0:

        preamble = text[:matches[0].start()].strip()

        if preamble:

            sections.append({
                "section": "Document Header",
                "text": preamble
            })

    for i, match in enumerate(matches):

        section_title = match.group(2).strip()

        start = match.start()

        if i + 1 < len(matches):
            end = matches[i + 1].start()
        else:
            end = len(text)

        section_text = text[start:end].strip()

        sections.append({
            "section": section_title,
            "text": section_text
        })

    return sections


# ============================================================
# 14. CHUNKING
# ============================================================
def chunk_text(
    text: str,
    chunk_size: int = CHUNK_SIZE,
    overlap: int = CHUNK_OVERLAP,
    min_chunk: int = MIN_CHUNK
) -> List[str]:
    """
    Character-based paragraph-aware chunking.

    - Target max chunk size = CHUNK_SIZE
    - Overlap between large chunks = CHUNK_OVERLAP
    - Ignore tiny chunks below MIN_CHUNK
    """

    text = text.strip()

    # Empty text
    if not text:
        return []

    # --------------------------------------------------------
    # Small section:
    # keep only if it is large enough
    # --------------------------------------------------------

    if len(text) <= chunk_size:

        if len(text) >= min_chunk:
            return [text]

        return []


    paragraphs = re.split(
        r"\n\s*\n",
        text
    )


    chunks = []

    current = ""


    for paragraph in paragraphs:

        paragraph = paragraph.strip()

        if not paragraph:
            continue


        candidate = (
            current
            + "\n\n"
            + paragraph
        ).strip()


        # ----------------------------------------------------
        # Paragraph fits inside current chunk
        # ----------------------------------------------------

        if len(candidate) <= chunk_size:

            current = candidate

            continue


        # ----------------------------------------------------
        # Save current chunk before starting new one
        # ----------------------------------------------------

        if current:

            if len(current.strip()) >= min_chunk:

                chunks.append(
                    current.strip()
                )


        # ----------------------------------------------------
        # Paragraph itself is larger than chunk size
        # ----------------------------------------------------

        if len(paragraph) > chunk_size:

            start = 0


            while start < len(paragraph):

                end = min(
                    start + chunk_size,
                    len(paragraph)
                )


                piece = paragraph[
                    start:end
                ].strip()


                if len(piece) >= min_chunk:

                    chunks.append(
                        piece
                    )


                if end >= len(paragraph):
                    break


                start = max(
                    end - overlap,
                    start + 1
                )


            current = ""


        # ----------------------------------------------------
        # Normal paragraph starts a new chunk
        # ----------------------------------------------------

        else:

            previous_tail = ""


            if chunks and overlap > 0:

                previous_tail = (
                    chunks[-1][
                        -overlap:
                    ]
                )


            current = (
                previous_tail
                + "\n\n"
                + paragraph
            ).strip()


    # --------------------------------------------------------
    # Final remaining chunk
    # --------------------------------------------------------

    if current:

        if len(current.strip()) >= min_chunk:

            chunks.append(
                current.strip()
            )


    return chunks

# ============================================================
# 15. EMBEDDING TEXT
# ============================================================

def build_embedding_text(
    chunk_text_value: str,
    metadata: Dict
) -> str:
    """
    Include useful semantic metadata in the embedding input.

    IDs/form numbers are deliberately NOT emphasized because
    they provide little semantic value.

    plan_name/state/product_type are useful because users may ask:
        "What does the Best Buy HMO cover?"
        "What are Maine HMO emergency benefits?"
        "What is the National Access EPO deductible?"
    """

    parts = []

    if metadata.get("plan_name"):
        parts.append(
            f"Plan: {metadata['plan_name']}"
        )

    if metadata.get("product_type") and \
       metadata["product_type"] != "UNKNOWN":

        parts.append(
            f"Product type: {metadata['product_type']}"
        )

    if metadata.get("plan_variant"):

        parts.append(
            f"Plan variant: {metadata['plan_variant']}"
        )

    if metadata.get("state"):

        parts.append(
            f"State: {metadata['state']}"
        )

    if metadata.get("section"):

        parts.append(
            f"Section: {metadata['section']}"
        )

    metadata_header = "\n".join(parts)

    if metadata_header:

        return (
            metadata_header +
            "\n\n" +
            chunk_text_value
        )

    return chunk_text_value


# ============================================================
# 16. PROCESS ONE MARKDOWN DOCUMENT
# ============================================================

def process_markdown_file(
    file_path: Path
) -> List[Dict]:

    text = file_path.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    text = normalize_whitespace(text)

    # --------------------------------------------------------
    # Document-level metadata
    # --------------------------------------------------------

    document_id = extract_document_id(text)

    plan_name = extract_plan_name(text)

    state = extract_state(text)

    effective_date = extract_effective_date(text)

    form_number = extract_form_number(text)

    product_type = extract_product_type(
        text=text,
        plan_name=plan_name
    )

    variants = extract_plan_variants(
        text=text,
        plan_name=plan_name
    )

    plan_variant = (
        " | ".join(variants)
        if variants
        else None
    )

    # --------------------------------------------------------
    # ID fallback
    # --------------------------------------------------------

    if not document_id:

        print(
            f"WARNING: no internal ID found: "
            f"{file_path.name}"
        )

        # Filename used ONLY as emergency fallback
        document_id = file_path.stem

    # --------------------------------------------------------
    # Sections
    # --------------------------------------------------------

    sections = split_into_sections(text)

    records = []

    global_chunk_number = 0

    for section_index, section in enumerate(
        sections,
        start=1
    ):

        section_name = section["section"]
        section_text = section["text"]

        section_chunks = chunk_text(
            section_text
        )

        for local_chunk_number, chunk in enumerate(
            section_chunks,
            start=1
        ):

            global_chunk_number += 1

            # Internal document ID + sequential chunk ID
            chunk_id = (
                f"{document_id}_chunk_"
                f"{global_chunk_number:04d}"
            )

            metadata = {

                "document_id": document_id,

                "chunk_id": chunk_id,

                "plan_name": plan_name,

                "state": state,

                "effective_date": effective_date,

                "form_number": form_number,

                "product_type": product_type,

                "plan_variant": plan_variant,

                "section": section_name,

                "section_index": section_index,

                "chunk_index": global_chunk_number,

                "source_file": file_path.name,
            }

            embedding_text = build_embedding_text(
                chunk_text_value=chunk,
                metadata=metadata
            )

            record = {

                # Azure Search-friendly unique ID
                "id": chunk_id,

                "document_id": document_id,

                "chunk_id": chunk_id,

                "plan_name": plan_name,

                "state": state,

                "effective_date": effective_date,

                "form_number": form_number,

                "product_type": product_type,

                "plan_variant": plan_variant,

                "section": section_name,

                "section_index": section_index,

                "chunk_index": global_chunk_number,

                "source_file": file_path.name,

                # Original text for citations / LLM response
                "text": chunk,

                # Text used for vector embedding
                "embedding_text": embedding_text,
            }

            records.append(record)

    return records


# ============================================================
# 17. PROCESS ALL FILES
# ============================================================

def process_folder(
    input_folder: Path,
    output_file: Path
):

    md_files = sorted(
        input_folder.rglob("*.md")
    )

    print(
        f"Found {len(md_files)} markdown files."
    )

    total_documents = 0
    total_chunks = 0

    product_counts = {}
    state_counts = {}
    missing_id_files = []

    with output_file.open(
        "w",
        encoding="utf-8"
    ) as writer:

        for file_path in md_files:

            try:

                records = process_markdown_file(
                    file_path
                )

                if not records:
                    continue

                total_documents += 1
                total_chunks += len(records)

                product = records[0][
                    "product_type"
                ]

                state = records[0][
                    "state"
                ] or "UNKNOWN"

                product_counts[product] = (
                    product_counts.get(
                        product,
                        0
                    ) + 1
                )

                state_counts[state] = (
                    state_counts.get(
                        state,
                        0
                    ) + 1
                )

                for record in records:

                    writer.write(
                        json.dumps(
                            record,
                            ensure_ascii=False
                        )
                        + "\n"
                    )

                print(
                    f"OK: {file_path.name}"
                    f" | ID={records[0]['document_id']}"
                    f" | Product={product}"
                    f" | State={state}"
                    f" | Chunks={len(records)}"
                )

            except Exception as e:

                print(
                    f"ERROR: {file_path.name}: {e}"
                )

    # ========================================================
    # SUMMARY
    # ========================================================

    print("\n" + "=" * 70)
    print("PROCESSING COMPLETE")
    print("=" * 70)

    print(
        f"Documents processed : {total_documents}"
    )

    print(
        f"Chunks created      : {total_chunks}"
    )

    print(
        f"Output              : {output_file}"
    )

    print("\nPRODUCT TYPE DISTRIBUTION")

    for product, count in sorted(
        product_counts.items(),
        key=lambda x: -x[1]
    ):

        print(
            f"  {product:<30} {count}"
        )

    print("\nSTATE DISTRIBUTION")

    for state, count in sorted(
        state_counts.items(),
        key=lambda x: -x[1]
    ):

        print(
            f"  {state:<30} {count}"
        )


# ============================================================
# 18. RUN
# ============================================================

if __name__ == "__main__":

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    process_folder(
        INPUT_FOLDER,
        OUTPUT_FILE
    )
