# -*- coding: utf-8 -*-
"""new_method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTRQIiVxPKTTqiRo54Y1Dx1X712ABo-s
"""

# -*- coding: utf-8 -*-

"""
Azure Document Intelligence
Document Normalization + Text/Table Chunking Pipeline

INPUTS for each document:
    ab_policy.md
    ab_policy.table.md   OR ab_policy_table.md
    ab_policy.json

OUTPUTS:
    normalized_documents/
        ab_policy.normalized.json
        ab_policy.normalized.md

    sob_chunks.jsonl

Pipeline:
    Document Intelligence outputs
            |
            +--> .md          -> prose + HTML tables
            +--> .table.md    -> Markdown tables
            +--> .json        -> structural metadata
            |
            v
        NORMALIZER
            |
            +--> HTML table <-> JSON table
            +--> Markdown table <-> JSON table
            +--> stable table_id
            +--> page number
            +--> section
            +--> surrounding context
            |
            v
       CHUNKING
            |
            +--> section-aware text chunks
            +--> row-aware table chunks
            |
            v
       JSONL for Azure AI Search
"""

import json
import re
import hashlib
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from difflib import SequenceMatcher

# BeautifulSoup is used only for reading HTML tables.
# pip install beautifulsoup4
from bs4 import BeautifulSoup


# ============================================================
# 1. CONFIGURATION
# ============================================================

INPUT_FOLDER = Path(
    r"C:\Users\mm7453\OneDrive - Health\workplace\adhoc\SOBs\all_extracted_files"
)

OUTPUT_FOLDER = INPUT_FOLDER.parent / "normalized_documents"

OUTPUT_JSONL = INPUT_FOLDER.parent / "sob_chunks.jsonl"


# Text chunk settings
MAX_TEXT_CHARS = 3500
TEXT_OVERLAP_CHARS = 400

# Table chunk settings
MAX_TABLE_ROWS_PER_CHUNK = 8

# Number of characters around the table to retain as context
TABLE_CONTEXT_CHARS = 800

# Matching thresholds
HTML_JSON_MATCH_THRESHOLD = 0.45
MARKDOWN_JSON_MATCH_THRESHOLD = 0.40


# ============================================================
# 2. BASIC TEXT UTILITIES
# ============================================================

def clean_whitespace(text: str) -> str:
    """Normalize whitespace without changing content."""
    if not text:
        return ""

    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    # Remove trailing whitespace
    text = "\n".join(line.rstrip() for line in text.splitlines())

    # Collapse excessive blank lines
    text = re.sub(r"\n{4,}", "\n\n\n", text)

    return text.strip()


def normalize_for_matching(text: str) -> str:
    """
    Normalize text for table matching.

    Used only for comparison — not for the final indexed content.
    """

    if not text:
        return ""

    text = text.lower()

    # Decode common HTML entities indirectly through BeautifulSoup
    text = BeautifulSoup(text, "html.parser").get_text(" ")

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text)

    # Remove most punctuation
    text = re.sub(r"[^a-z0-9%$.,:/\- ]+", " ", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()


def stable_hash(text: str, length: int = 10) -> str:
    return hashlib.md5(
        text.encode("utf-8", errors="ignore")
    ).hexdigest()[:length]


# ============================================================
# 3. DOCUMENT NAME / FILE DISCOVERY
# ============================================================

def discover_documents(input_folder: Path) -> List[Dict]:

    documents = []

    for md_file in sorted(input_folder.glob("*.md")):

        name = md_file.name.lower()

        # Ignore table-only Markdown files
        if name.endswith(".table.md"):
            continue

        if name.endswith("_table.md"):
            continue

        base_name = md_file.stem

        json_file = input_folder / f"{base_name}.json"

        table_candidates = [
            input_folder / f"{base_name}.table.md",
            input_folder / f"{base_name}_table.md",
        ]

        table_md_file = None

        for candidate in table_candidates:
            if candidate.exists():
                table_md_file = candidate
                break

        if not json_file.exists():
            print(
                f"WARNING: JSON missing for {base_name}. "
                f"Skipping document."
            )
            continue

        if table_md_file is None:
            print(
                f"WARNING: Table Markdown missing for {base_name}. "
                f"Will continue using JSON tables."
            )

        documents.append(
            {
                "document_id": base_name,
                "body_md": md_file,
                "table_md": table_md_file,
                "json": json_file,
            }
        )

    return documents


# ============================================================
# 4. HTML TABLE EXTRACTION FROM BODY MARKDOWN
# ============================================================

HTML_TABLE_PATTERN = re.compile(
    r"<table\b[^>]*>.*?</table>",
    flags=re.IGNORECASE | re.DOTALL
)


def extract_html_tables(markdown_text: str) -> List[Dict]:

    tables = []

    for index, match in enumerate(
        HTML_TABLE_PATTERN.finditer(markdown_text)
    ):

        html = match.group(0)

        soup = BeautifulSoup(html, "html.parser")

        rows = []

        for tr in soup.find_all("tr"):

            cells = []

            for cell in tr.find_all(["th", "td"]):
                value = clean_whitespace(
                    cell.get_text(" ", strip=True)
                )
                cells.append(value)

            if cells:
                rows.append(cells)

        flat_text = " ".join(
            cell
            for row in rows
            for cell in row
        )

        tables.append(
            {
                "html_index": index,
                "html": html,
                "rows": rows,
                "text": flat_text,
                "normalized_text": normalize_for_matching(flat_text),
                "start": match.start(),
                "end": match.end(),
            }
        )

    return tables


# ============================================================
# 5. MARKDOWN TABLE EXTRACTION
# ============================================================

def is_markdown_separator(line: str) -> bool:

    line = line.strip()

    if "|" not in line:
        return False

    cells = [
        x.strip()
        for x in line.strip("|").split("|")
    ]

    if not cells:
        return False

    return all(
        re.fullmatch(r":?-{3,}:?", cell or "")
        for cell in cells
    )


def parse_markdown_row(line: str) -> List[str]:

    return [
        cell.strip()
        for cell in line.strip().strip("|").split("|")
    ]


def extract_markdown_tables(text: str) -> List[Dict]:

    if not text:
        return []

    lines = text.splitlines()

    tables = []

    i = 0

    while i < len(lines) - 1:

        current = lines[i]
        next_line = lines[i + 1]

        if (
            "|" in current
            and is_markdown_separator(next_line)
        ):

            block_lines = [
                current,
                next_line,
            ]

            j = i + 2

            while j < len(lines):

                line = lines[j]

                if "|" not in line:
                    break

                if not line.strip():
                    break

                block_lines.append(line)

                j += 1

            markdown = "\n".join(block_lines)

            header = parse_markdown_row(block_lines[0])

            rows = []

            for line in block_lines[2:]:
                rows.append(parse_markdown_row(line))

            flat_text = " ".join(
                header
                + [
                    cell
                    for row in rows
                    for cell in row
                ]
            )

            tables.append(
                {
                    "markdown_index": len(tables),
                    "markdown": markdown,
                    "header": header,
                    "rows": rows,
                    "text": flat_text,
                    "normalized_text": normalize_for_matching(flat_text),
                }
            )

            i = j

        else:
            i += 1

    return tables


# ============================================================
# 6. AZURE DOCUMENT INTELLIGENCE JSON
# ============================================================

def get_analyze_result(data: Dict) -> Dict:
    """
    Azure REST responses are sometimes stored as:

        {
            "status": "...",
            "analyzeResult": {...}
        }

    and sometimes only analyzeResult is saved.
    """

    if "analyzeResult" in data:
        return data["analyzeResult"]

    return data


def get_json_table_page(table: Dict) -> Optional[int]:

    bounding_regions = (
        table.get("boundingRegions")
        or table.get("bounding_regions")
        or []
    )

    if bounding_regions:

        region = bounding_regions[0]

        return (
            region.get("pageNumber")
            or region.get("page_number")
        )

    return None


def extract_json_tables(json_data: Dict) -> List[Dict]:

    analyze_result = get_analyze_result(json_data)

    raw_tables = analyze_result.get("tables", [])

    tables = []

    for index, table in enumerate(raw_tables):

        cells = table.get("cells", [])

        parsed_cells = []

        max_row = 0
        max_col = 0

        for cell in cells:

            row_index = (
                cell.get("rowIndex")
                if "rowIndex" in cell
                else cell.get("row_index", 0)
            )

            col_index = (
                cell.get("columnIndex")
                if "columnIndex" in cell
                else cell.get("column_index", 0)
            )

            row_span = (
                cell.get("rowSpan")
                or cell.get("row_span")
                or 1
            )

            col_span = (
                cell.get("columnSpan")
                or cell.get("column_span")
                or 1
            )

            content = clean_whitespace(
                cell.get("content", "")
            )

            kind = (
                cell.get("kind")
                or cell.get("cellKind")
                or ""
            )

            parsed_cells.append(
                {
                    "row": row_index,
                    "column": col_index,
                    "row_span": row_span,
                    "column_span": col_span,
                    "content": content,
                    "kind": kind,
                }
            )

            max_row = max(max_row, row_index)
            max_col = max(max_col, col_index)

        rows = [
            [""] * (max_col + 1)
            for _ in range(max_row + 1)
        ]

        for cell in parsed_cells:

            r = cell["row"]
            c = cell["column"]

            if r < len(rows) and c < len(rows[r]):
                rows[r][c] = cell["content"]

        flat_text = " ".join(
            cell
            for row in rows
            for cell in row
            if cell
        )

        spans = table.get("spans", [])

        span_offset = None
        span_length = None

        if spans:

            span_offset = spans[0].get("offset")
            span_length = spans[0].get("length")

        page_number = get_json_table_page(table)

        tables.append(
            {
                "json_index": index,
                "page_number": page_number,
                "row_count": table.get(
                    "rowCount",
                    table.get("row_count", len(rows))
                ),
                "column_count": table.get(
                    "columnCount",
                    table.get(
                        "column_count",
                        max_col + 1
                    )
                ),
                "cells": parsed_cells,
                "rows": rows,
                "text": flat_text,
                "normalized_text": normalize_for_matching(flat_text),
                "span_offset": span_offset,
                "span_length": span_length,
                "raw_table": table,
            }
        )

    return tables


# ============================================================
# 7. SIMILARITY / TABLE MATCHING
# ============================================================

def token_jaccard(a: str, b: str) -> float:

    tokens_a = set(a.split())
    tokens_b = set(b.split())

    if not tokens_a or not tokens_b:
        return 0.0

    intersection = len(tokens_a & tokens_b)
    union = len(tokens_a | tokens_b)

    return intersection / union


def sequence_similarity(a: str, b: str) -> float:

    if not a or not b:
        return 0.0

    return SequenceMatcher(
        None,
        a,
        b,
    ).ratio()


def table_similarity(a: str, b: str) -> float:

    if not a or not b:
        return 0.0

    jaccard = token_jaccard(a, b)
    sequence = sequence_similarity(a, b)

    # Token overlap is more important than exact formatting/order.
    return (
        0.70 * jaccard
        + 0.30 * sequence
    )


def best_unused_match(
    source_text: str,
    candidates: List[Dict],
    used_indices: set,
    index_field: str,
) -> Tuple[Optional[int], float]:

    best_index = None
    best_score = -1.0

    for candidate in candidates:

        candidate_index = candidate[index_field]

        if candidate_index in used_indices:
            continue

        score = table_similarity(
            source_text,
            candidate["normalized_text"]
        )

        if score > best_score:
            best_score = score
            best_index = candidate_index

    return best_index, best_score


# ============================================================
# 8. SECTION / HEADING DETECTION
# ============================================================

HEADING_PATTERN = re.compile(
    r"^(#{1,6})\s+(.+?)\s*$",
    flags=re.MULTILINE
)


def extract_headings(markdown_text: str) -> List[Dict]:

    headings = []

    for match in HEADING_PATTERN.finditer(markdown_text):

        headings.append(
            {
                "position": match.start(),
                "level": len(match.group(1)),
                "text": clean_whitespace(match.group(2)),
            }
        )

    return headings


def section_at_position(
    headings: List[Dict],
    position: int
) -> Optional[str]:

    previous = [
        heading
        for heading in headings
        if heading["position"] <= position
    ]

    if not previous:
        return None

    return previous[-1]["text"]


# ============================================================
# 9. TABLE SURROUNDING CONTEXT
# ============================================================

def context_before(
    text: str,
    position: int,
    chars: int = TABLE_CONTEXT_CHARS
) -> str:

    segment = text[
        max(0, position - chars):
        position
    ]

    # Remove HTML tags from context
    segment = BeautifulSoup(
        segment,
        "html.parser"
    ).get_text("\n")

    return clean_whitespace(segment)


def context_after(
    text: str,
    position: int,
    chars: int = TABLE_CONTEXT_CHARS
) -> str:

    segment = text[
        position:
        min(len(text), position + chars)
    ]

    segment = BeautifulSoup(
        segment,
        "html.parser"
    ).get_text("\n")

    return clean_whitespace(segment)


# ============================================================
# 10. JSON TABLE -> MARKDOWN FALLBACK
# ============================================================

def escape_md_cell(value: str) -> str:

    value = str(value or "")
    value = value.replace("|", "\\|")
    value = value.replace("\n", " ")

    return value.strip()


def rows_to_markdown(rows: List[List[str]]) -> str:

    if not rows:
        return ""

    max_cols = max(len(row) for row in rows)

    normalized_rows = []

    for row in rows:

        row = row + [""] * (
            max_cols - len(row)
        )

        normalized_rows.append(row)

    header = normalized_rows[0]

    output = []

    output.append(
        "| "
        + " | ".join(
            escape_md_cell(cell)
            for cell in header
        )
        + " |"
    )

    output.append(
        "| "
        + " | ".join(
            "---"
            for _ in range(max_cols)
        )
        + " |"
    )

    for row in normalized_rows[1:]:

        output.append(
            "| "
            + " | ".join(
                escape_md_cell(cell)
                for cell in row
            )
            + " |"
        )

    return "\n".join(output)


# ============================================================
# 11. BUILD NORMALIZED TABLE OBJECTS
# ============================================================

def build_normalized_tables(
    document_id: str,
    body_md: str,
    html_tables: List[Dict],
    markdown_tables: List[Dict],
    json_tables: List[Dict],
) -> List[Dict]:

    headings = extract_headings(body_md)

    used_html = set()
    used_markdown = set()

    normalized_tables = []

    for json_table in json_tables:

        json_index = json_table["json_index"]

        table_id = (
            f"{document_id}_table_"
            f"{json_index + 1:04d}"
        )

        # --------------------------------------------
        # Match JSON table -> HTML table
        # --------------------------------------------

        html_index, html_score = best_unused_match(
            json_table["normalized_text"],
            html_tables,
            used_html,
            "html_index"
        )

        matched_html = None

        if (
            html_index is not None
            and html_score >= HTML_JSON_MATCH_THRESHOLD
        ):

            matched_html = next(
                item
                for item in html_tables
                if item["html_index"] == html_index
            )

            used_html.add(html_index)

        # Position-based fallback
        elif (
            json_index < len(html_tables)
            and json_index not in used_html
        ):

            matched_html = html_tables[json_index]

            html_index = json_index

            html_score = table_similarity(
                json_table["normalized_text"],
                matched_html["normalized_text"]
            )

            used_html.add(html_index)

        # --------------------------------------------
        # Match JSON -> Markdown table
        # --------------------------------------------

        md_index, md_score = best_unused_match(
            json_table["normalized_text"],
            markdown_tables,
            used_markdown,
            "markdown_index"
        )

        matched_markdown = None

        if (
            md_index is not None
            and md_score >= MARKDOWN_JSON_MATCH_THRESHOLD
        ):

            matched_markdown = next(
                item
                for item in markdown_tables
                if item["markdown_index"] == md_index
            )

            used_markdown.add(md_index)

        # Position fallback
        elif (
            json_index < len(markdown_tables)
            and json_index not in used_markdown
        ):

            matched_markdown = markdown_tables[json_index]

            md_index = json_index

            md_score = table_similarity(
                json_table["normalized_text"],
                matched_markdown["normalized_text"]
            )

            used_markdown.add(md_index)

        # --------------------------------------------
        # Determine location/context
        # --------------------------------------------

        if matched_html:

            position = matched_html["start"]

            section = section_at_position(
                headings,
                position
            )

            preceding_context = context_before(
                body_md,
                matched_html["start"]
            )

            following_context = context_after(
                body_md,
                matched_html["end"]
            )

        else:

            position = None
            section = None
            preceding_context = ""
            following_context = ""

        # --------------------------------------------
        # Preferred table representation
        # --------------------------------------------

        if matched_markdown:

            table_markdown = matched_markdown["markdown"]
            table_source = "table_md"

        else:

            # Fallback if table.md failed/missing
            table_markdown = rows_to_markdown(
                json_table["rows"]
            )

            table_source = "document_intelligence_json"

        normalized_tables.append(
            {
                "table_id": table_id,
                "table_number": json_index + 1,

                "page_number": json_table["page_number"],

                "section": section,

                "row_count": json_table["row_count"],
                "column_count": json_table["column_count"],

                "span_offset": json_table["span_offset"],
                "span_length": json_table["span_length"],

                "table_markdown": table_markdown,
                "table_source": table_source,

                "json_rows": json_table["rows"],

                "preceding_context": preceding_context,
                "following_context": following_context,

                "html_match_score": round(
                    max(html_score, 0),
                    4
                ),

                "markdown_match_score": round(
                    max(md_score, 0),
                    4
                ),

                "html_index": (
                    matched_html["html_index"]
                    if matched_html
                    else None
                ),

                "markdown_index": (
                    matched_markdown["markdown_index"]
                    if matched_markdown
                    else None
                ),

                "body_position": position,
            }
        )

    return normalized_tables


# ============================================================
# 12. REPLACE HTML TABLES WITH TABLE_ID PLACEHOLDERS
# ============================================================

def replace_html_with_placeholders(
    body_md: str,
    normalized_tables: List[Dict]
) -> str:

    replacements = []

    for table in normalized_tables:

        position = table.get("body_position")

        html_index = table.get("html_index")

        if position is None or html_index is None:
            continue

        replacements.append(table)

    # Need fresh HTML positions
    html_tables = extract_html_tables(body_md)

    replacement_map = {
        table["html_index"]: table["table_id"]
        for table in replacements
    }

    pieces = []

    last_position = 0

    for html_table in html_tables:

        start = html_table["start"]
        end = html_table["end"]
        index = html_table["html_index"]

        pieces.append(
            body_md[last_position:start]
        )

        if index in replacement_map:

            table_id = replacement_map[index]

            pieces.append(
                f"\n\n[TABLE: {table_id}]\n\n"
            )

        else:

            # Keep unmatched table instead of deleting data
            pieces.append(html_table["html"])

        last_position = end

    pieces.append(body_md[last_position:])

    return clean_whitespace(
        "".join(pieces)
    )


# ============================================================
# 13. SECTION-AWARE TEXT SPLITTING
# ============================================================

def split_into_sections(text: str) -> List[Dict]:

    headings = list(
        HEADING_PATTERN.finditer(text)
    )

    if not headings:

        return [
            {
                "section": None,
                "level": None,
                "content": text,
            }
        ]

    sections = []

    # Content before first heading
    if headings[0].start() > 0:

        intro = text[:headings[0].start()].strip()

        if intro:
            sections.append(
                {
                    "section": "Document Introduction",
                    "level": 0,
                    "content": intro,
                }
            )

    for index, heading in enumerate(headings):

        start = heading.end()

        if index + 1 < len(headings):
            end = headings[index + 1].start()
        else:
            end = len(text)

        heading_text = clean_whitespace(
            heading.group(2)
        )

        content = text[start:end].strip()

        sections.append(
            {
                "section": heading_text,
                "level": len(heading.group(1)),
                "content": content,
            }
        )

    return sections


# ============================================================
# 14. TEXT CHUNKING
# ============================================================

def split_long_text(
    text: str,
    max_chars: int,
    overlap_chars: int,
) -> List[str]:

    text = clean_whitespace(text)

    if len(text) <= max_chars:
        return [text] if text else []

    paragraphs = re.split(
        r"\n\s*\n",
        text
    )

    chunks = []

    current = ""

    for paragraph in paragraphs:

        paragraph = paragraph.strip()

        if not paragraph:
            continue

        proposed = (
            current
            + "\n\n"
            + paragraph
            if current
            else paragraph
        )

        if len(proposed) <= max_chars:

            current = proposed

        else:

            if current:
                chunks.append(current)

            # Very large paragraph
            if len(paragraph) > max_chars:

                start = 0

                while start < len(paragraph):

                    end = min(
                        start + max_chars,
                        len(paragraph)
                    )

                    chunk = paragraph[start:end]

                    chunks.append(chunk)

                    if end == len(paragraph):
                        break

                    start = max(
                        0,
                        end - overlap_chars
                    )

                current = ""

            else:

                # Carry trailing overlap from previous chunk
                if chunks and overlap_chars > 0:

                    overlap = chunks[-1][
                        -overlap_chars:
                    ]

                    current = (
                        overlap
                        + "\n\n"
                        + paragraph
                    )

                    if len(current) > max_chars:
                        current = paragraph

                else:
                    current = paragraph

    if current:
        chunks.append(current)

    return chunks


def create_text_chunks(
    document_id: str,
    normalized_text: str
) -> List[Dict]:

    sections = split_into_sections(
        normalized_text
    )

    chunks = []

    chunk_counter = 1

    for section in sections:

        section_name = section["section"]
        content = section["content"]

        pieces = split_long_text(
            content,
            MAX_TEXT_CHARS,
            TEXT_OVERLAP_CHARS,
        )

        for piece in pieces:

            if not piece.strip():
                continue

            chunk_id = (
                f"{document_id}_text_"
                f"{chunk_counter:05d}"
            )

            # Include section in searchable content
            if section_name:

                searchable_content = (
                    f"Section: {section_name}\n\n"
                    f"{piece}"
                )

            else:

                searchable_content = piece

            chunks.append(
                {
                    "chunk_id": chunk_id,
                    "document_id": document_id,

                    "chunk_type": "text",

                    "content_source": "document_body",

                    "section": section_name,

                    "page_number": None,

                    "table_id": None,

                    "content": searchable_content,

                    "metadata": {
                        "section_level": section["level"]
                    },
                }
            )

            chunk_counter += 1

    return chunks


# ============================================================
# 15. TABLE ROW CHUNKING
# ============================================================

def markdown_table_chunk(
    header: List[str],
    rows: List[List[str]]
) -> str:

    all_rows = [header] + rows

    return rows_to_markdown(all_rows)


def create_table_chunks(
    document_id: str,
    tables: List[Dict]
) -> List[Dict]:

    chunks = []

    counter = 1

    for table in tables:

        rows = table["json_rows"]

        if not rows:
            continue

        header = rows[0]

        body_rows = rows[1:]

        # A one-row table is still kept
        if not body_rows:

            row_groups = [[]]

        else:

            row_groups = [
                body_rows[i:i + MAX_TABLE_ROWS_PER_CHUNK]
                for i in range(
                    0,
                    len(body_rows),
                    MAX_TABLE_ROWS_PER_CHUNK
                )
            ]

        for group_number, group in enumerate(
            row_groups,
            start=1
        ):

            table_md = markdown_table_chunk(
                header,
                group
            )

            context_parts = []

            if table["section"]:

                context_parts.append(
                    f"Section: {table['section']}"
                )

            if table["preceding_context"]:

                context_parts.append(
                    "Context before table:\n"
                    + table["preceding_context"]
                )

            context_parts.append(
                "Table:\n"
                + table_md
            )

            if table["following_context"]:

                context_parts.append(
                    "Context after table:\n"
                    + table["following_context"]
                )

            content = "\n\n".join(
                context_parts
            )

            chunk_id = (
                f"{document_id}_table_"
                f"{counter:05d}"
            )

            chunks.append(
                {
                    "chunk_id": chunk_id,

                    "document_id": document_id,

                    "chunk_type": "table",

                    "content_source": "normalized_table",

                    "section": table["section"],

                    "page_number": table["page_number"],

                    "table_id": table["table_id"],

                    "table_part": group_number,

                    "content": content,

                    "metadata": {
                        "row_count": table["row_count"],
                        "column_count": table["column_count"],

                        "table_source": table["table_source"],

                        "html_match_score":
                            table["html_match_score"],

                        "markdown_match_score":
                            table["markdown_match_score"],
                    },
                }
            )

            counter += 1

    return chunks


# ============================================================
# 16. ADD PREVIOUS / NEXT CHUNK REFERENCES
# ============================================================

def add_chunk_links(chunks: List[Dict]) -> List[Dict]:

    for index, chunk in enumerate(chunks):

        if index > 0:
            chunk["previous_chunk_id"] = (
                chunks[index - 1]["chunk_id"]
            )
        else:
            chunk["previous_chunk_id"] = None

        if index < len(chunks) - 1:
            chunk["next_chunk_id"] = (
                chunks[index + 1]["chunk_id"]
            )
        else:
            chunk["next_chunk_id"] = None

    return chunks


# ============================================================
# 17. PROCESS ONE DOCUMENT
# ============================================================

def process_document(files: Dict):

    document_id = files["document_id"]

    print()
    print("=" * 70)
    print(f"Processing: {document_id}")
    print("=" * 70)

    # --------------------------------------------------------
    # Read source files
    # --------------------------------------------------------

    body_md = files["body_md"].read_text(
        encoding="utf-8",
        errors="ignore"
    )

    body_md = clean_whitespace(body_md)

    if files["table_md"]:

        table_md_text = files["table_md"].read_text(
            encoding="utf-8",
            errors="ignore"
        )

    else:

        table_md_text = ""

    with open(
        files["json"],
        "r",
        encoding="utf-8"
    ) as f:

        json_data = json.load(f)

    # --------------------------------------------------------
    # Extract representations
    # --------------------------------------------------------

    html_tables = extract_html_tables(
        body_md
    )

    markdown_tables = extract_markdown_tables(
        table_md_text
    )

    json_tables = extract_json_tables(
        json_data
    )

    print(
        f"HTML tables      : {len(html_tables)}"
    )

    print(
        f"Markdown tables  : {len(markdown_tables)}"
    )

    print(
        f"JSON tables      : {len(json_tables)}"
    )

    # --------------------------------------------------------
    # Match all table representations
    # --------------------------------------------------------

    normalized_tables = build_normalized_tables(
        document_id=document_id,
        body_md=body_md,
        html_tables=html_tables,
        markdown_tables=markdown_tables,
        json_tables=json_tables,
    )

    # --------------------------------------------------------
    # Replace duplicate HTML table with table ID
    # --------------------------------------------------------

    normalized_text = replace_html_with_placeholders(
        body_md,
        normalized_tables
    )

    # --------------------------------------------------------
    # Final normalized object
    # --------------------------------------------------------

    normalized_document = {

        "document_id": document_id,

        "source_files": {
            "body_markdown":
                files["body_md"].name,

            "table_markdown":
                (
                    files["table_md"].name
                    if files["table_md"]
                    else None
                ),

            "document_intelligence_json":
                files["json"].name,
        },

        "body": normalized_text,

        "tables": normalized_tables,

        "statistics": {
            "html_table_count":
                len(html_tables),

            "markdown_table_count":
                len(markdown_tables),

            "json_table_count":
                len(json_tables),

            "normalized_table_count":
                len(normalized_tables),
        },
    }

    # --------------------------------------------------------
    # Save normalized JSON
    # --------------------------------------------------------

    OUTPUT_FOLDER.mkdir(
        parents=True,
        exist_ok=True
    )

    json_output = (
        OUTPUT_FOLDER
        / f"{document_id}.normalized.json"
    )

    with open(
        json_output,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            normalized_document,
            f,
            ensure_ascii=False,
            indent=2
        )

    # --------------------------------------------------------
    # Save normalized Markdown for inspection/debugging
    # --------------------------------------------------------

    md_output = (
        OUTPUT_FOLDER
        / f"{document_id}.normalized.md"
    )

    md_output.write_text(
        normalized_text,
        encoding="utf-8"
    )

    # --------------------------------------------------------
    # Chunk
    # --------------------------------------------------------

    text_chunks = create_text_chunks(
        document_id,
        normalized_text
    )

    table_chunks = create_table_chunks(
        document_id,
        normalized_tables
    )

    all_chunks = (
        text_chunks
        + table_chunks
    )

    all_chunks = add_chunk_links(
        all_chunks
    )

    print(
        f"Text chunks      : {len(text_chunks)}"
    )

    print(
        f"Table chunks     : {len(table_chunks)}"
    )

    print(
        f"Total chunks     : {len(all_chunks)}"
    )

    return normalized_document, all_chunks


# ============================================================
# 18. PROCESS ALL DOCUMENTS
# ============================================================

def main():

    OUTPUT_FOLDER.mkdir(
        parents=True,
        exist_ok=True
    )

    documents = discover_documents(
        INPUT_FOLDER
    )

    print(
        f"\nDocuments discovered: {len(documents)}"
    )

    all_chunks = []

    for files in documents:

        try:

            _, chunks = process_document(
                files
            )

            all_chunks.extend(chunks)

        except Exception as e:

            print(
                f"\nERROR processing "
                f"{files['document_id']}: {e}"
            )

    # --------------------------------------------------------
    # Write final JSONL
    # --------------------------------------------------------

    with open(
        OUTPUT_JSONL,
        "w",
        encoding="utf-8"
    ) as f:

        for chunk in all_chunks:

            f.write(
                json.dumps(
                    chunk,
                    ensure_ascii=False
                )
                + "\n"
            )

    print()
    print("=" * 70)
    print("PIPELINE COMPLETE")
    print("=" * 70)

    print(
        f"Normalized documents:\n"
        f"{OUTPUT_FOLDER}"
    )

    print(
        f"\nJSONL chunks:\n"
        f"{OUTPUT_JSONL}"
    )

    print(
        f"\nTotal chunks: "
        f"{len(all_chunks)}"
    )


# ============================================================
# 19. RUN
# ============================================================

if __name__ == "__main__":
    main()