# -*- coding: utf-8 -*-
"""normalize_documents_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCVeawiXK-HdvS4-BE7XlVKBBp-mc-Bl
"""

# -*- coding: utf-8 -*-

"""
normalize_documents_v3.py

============================================================
 SOB DOCUMENT NORMALIZER - V3
============================================================

INPUT PER DOCUMENT
------------------
Example:

MD0000005930.md
MD0000005930.table.md
MD0000005930.json

PRIMARY PURPOSE
---------------
1. Read Azure Document Intelligence JSON.
2. Reconstruct tables using:
      rowIndex
      columnIndex
      rowSpan
      columnSpan
      cell kind
      boundingRegions
3. Normalize table structure.
4. Detect:
      - column headers
      - category rows
      - benefit rows
5. Propagate category values to child benefit rows.
6. Preserve provenance:
      - document_id
      - page_number
      - table_id
      - row_number
      - bounding_regions
7. Validate tables.
8. Produce:
      - clean_normalized.md
      - normalized.json
      - normalized_tables.md
9. Keep page metadata in Markdown:
      <!-- PageFooter="..." -->
      <!-- PageNumber="..." -->
      <!-- PageBreak -->

IMPORTANT
---------
The normalized JSON is the authoritative structured representation
for table chunking.

The Markdown version is primarily for:
    - inspection
    - debugging
    - human validation
    - text chunking

============================================================
"""

from pathlib import Path
import json
import re
from typing import Dict, List, Optional, Any, Tuple
from copy import deepcopy


# ============================================================
# 1. CONFIGURATION
# ============================================================

INPUT_FOLDER = Path(
    r"C:\Users\mm7453\OneDrive - Health\workplace\adhoc\SOBs\document_intelligence_output"
)

OUTPUT_FOLDER = INPUT_FOLDER.parent / "normalized_documents_v3"

OUTPUT_FOLDER.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 2. SETTINGS
# ============================================================

# Keep these extraction artifacts because they are useful
# for provenance / citation / debugging.

KEEP_PAGE_METADATA = True

# We do NOT delete these sections during normalization.
#
# If desired, they can later be filtered during CHUNKING.
#
# This is safer because metadata extraction may depend on
# information contained in the original normalized document.

REMOVE_LARGE_NOISE_SECTIONS = False


# ============================================================
# 3. BASIC TEXT UTILITIES
# ============================================================

def normalize_line_endings(text: str) -> str:

    return (
        text
        .replace("\r\n", "\n")
        .replace("\r", "\n")
    )


def normalize_spaces(text: str) -> str:
    """
    Normalize spaces inside extracted cell values.
    """

    if text is None:
        return ""

    text = str(text)

    text = text.replace("\xa0", " ")

    text = re.sub(
        r"[ \t]+",
        " ",
        text
    )

    text = re.sub(
        r"\s*\n\s*",
        " ",
        text
    )

    return text.strip()


# ============================================================
# 4. REMOVE MARKDOWN LINKS
# ============================================================

def remove_markdown_links(text: str) -> str:

    return re.sub(
        r"\[([^\]]+)\]\((.*?)\)",
        r"\1",
        text
    )


# ============================================================
# 5. REMOVE REPEATED COMPANY HEADERS
# ============================================================

def remove_repeated_headers(text: str) -> str:

    patterns = [

        r"(?im)^\s*Harvard Pilgrim Health Care\s*$",

        r"(?im)^\s*Harvard Pilgrim Health Care,\s*Inc\.\s*$",

        r"(?im)^\s*Harvard Pilgrim Health Care of New England,\s*Inc\.\s*$",

    ]

    for pattern in patterns:

        text = re.sub(
            pattern,
            "",
            text
        )

    return text


# ============================================================
# 6. REMOVE IMMEDIATE DUPLICATE LINES
# ============================================================

def remove_duplicate_lines(text: str) -> str:

    lines = text.splitlines()

    output = []

    previous = None

    for line in lines:

        current = line.strip()

        if current == previous and current:
            continue

        output.append(line)

        previous = current

    return "\n".join(output)


# ============================================================
# 7. CLEAN EXCESS WHITESPACE
# ============================================================

def clean_whitespace(text: str) -> str:

    text = re.sub(
        r"\n{4,}",
        "\n\n\n",
        text
    )

    return text.strip() + "\n"


# ============================================================
# 8. CLEAN MARKDOWN DOCUMENT
# ============================================================

def clean_document_markdown(text: str) -> str:

    text = normalize_line_endings(text)

    text = remove_markdown_links(text)

    text = remove_repeated_headers(text)

    text = remove_duplicate_lines(text)

    text = clean_whitespace(text)

    return text


# ============================================================
# 9. FIND ANALYZE RESULT IN AZURE JSON
# ============================================================

def get_analyze_result(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Azure DI JSON can appear either as:

        {
            "analyzeResult": {...}
        }

    or the analyze result itself.

    Support both.
    """

    if "analyzeResult" in data:
        return data["analyzeResult"]

    return data


# ============================================================
# 10. DOCUMENT ID EXTRACTION
# ============================================================

def extract_document_id(
    md_text: str,
    source_path: Path
) -> str:

    patterns = [

        # Example:
        # <!-- PageHeader="ID: MD0000005930" -->

        r'(?i)PageHeader=.*?\bID\s*[:#]?\s*([A-Z]{1,5}\d{5,})',

        # ID: MD0000005930

        r'(?im)^\s*ID\s*[:#]?\s*([A-Z]{1,5}\d{5,})\s*$',

        # Generic standalone ID

        r'\b(MD\d{6,})\b',

        r'\b(DN\d{6,})\b',

        r'\b(ID\d{6,})\b',

    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            md_text
        )

        if match:

            return match.group(1).strip()

    # fallback to filename

    filename_match = re.search(
        r'([A-Za-z]{1,5}\d{5,})',
        source_path.stem
    )

    if filename_match:
        return filename_match.group(1)

    return source_path.stem


# ============================================================
# 11. PAGE NUMBER FROM BOUNDING REGIONS
# ============================================================

def get_page_number(
    bounding_regions: Optional[List[Dict[str, Any]]]
) -> Optional[int]:

    if not bounding_regions:
        return None

    first = bounding_regions[0]

    return first.get(
        "pageNumber"
    )


# ============================================================
# 12. BUILD EMPTY GRID
# ============================================================

def create_grid(
    rows: int,
    columns: int
) -> List[List[Optional[Dict[str, Any]]]]:

    return [
        [None for _ in range(columns)]
        for _ in range(rows)
    ]


# ============================================================
# 13. NORMALIZE AZURE CELL
# ============================================================

def normalize_azure_cell(
    cell: Dict[str, Any]
) -> Dict[str, Any]:

    return {

        "content":
            normalize_spaces(
                cell.get("content", "")
            ),

        "row_index":
            cell.get("rowIndex", 0),

        "column_index":
            cell.get("columnIndex", 0),

        "row_span":
            cell.get("rowSpan", 1) or 1,

        "column_span":
            cell.get("columnSpan", 1) or 1,

        "kind":
            cell.get("kind", "content"),

        "bounding_regions":
            cell.get("boundingRegions", []),

        "spans":
            cell.get("spans", []),

        "elements":
            cell.get("elements", []),
    }


# ============================================================
# 14. RECONSTRUCT TABLE GRID
# ============================================================

def reconstruct_table_grid(
    table: Dict[str, Any]
) -> List[List[Optional[Dict[str, Any]]]]:

    row_count = table.get(
        "rowCount",
        0
    )

    column_count = table.get(
        "columnCount",
        0
    )

    grid = create_grid(
        row_count,
        column_count
    )

    for raw_cell in table.get(
        "cells",
        []
    ):

        cell = normalize_azure_cell(
            raw_cell
        )

        row_index = cell["row_index"]

        column_index = cell["column_index"]

        row_span = cell["row_span"]

        column_span = cell["column_span"]

        for r in range(
            row_index,
            min(
                row_index + row_span,
                row_count
            )
        ):

            for c in range(
                column_index,
                min(
                    column_index + column_span,
                    column_count
                )
            ):

                copied_cell = deepcopy(
                    cell
                )

                copied_cell["is_span_origin"] = (
                    r == row_index
                    and
                    c == column_index
                )

                grid[r][c] = copied_cell

    return grid


# ============================================================
# 15. GET GRID VALUE
# ============================================================

def grid_value(
    cell: Optional[Dict[str, Any]]
) -> str:

    if not cell:
        return ""

    return normalize_spaces(
        cell.get(
            "content",
            ""
        )
    )


# ============================================================
# 16. CONVERT GRID INTO SIMPLE ROWS
# ============================================================

def grid_to_rows(
    grid: List[List[Optional[Dict[str, Any]]]]
) -> List[List[str]]:

    rows = []

    for row in grid:

        values = [
            grid_value(cell)
            for cell in row
        ]

        rows.append(values)

    return rows


# ============================================================
# 17. DETECT HEADER ROW
# ============================================================

def is_header_row(
    grid_row: List[Optional[Dict[str, Any]]]
) -> bool:

    kinds = []

    for cell in grid_row:

        if cell:

            kinds.append(
                cell.get(
                    "kind",
                    ""
                )
            )

    header_kinds = {
        "columnHeader",
        "rowHeader",
        "stubHead"
    }

    return any(
        kind in header_kinds
        for kind in kinds
    )


# ============================================================
# 18. FIND PRIMARY HEADER ROW
# ============================================================

def find_header_row(
    grid: List[List[Optional[Dict[str, Any]]]]
) -> int:
    """
    Prefer Azure's explicit columnHeader information.

    Otherwise choose first non-empty row.
    """

    for index, row in enumerate(grid):

        if is_header_row(row):

            return index

    for index, row in enumerate(grid):

        values = [
            grid_value(cell)
            for cell in row
        ]

        if any(values):
            return index

    return 0


# ============================================================
# 19. NORMALIZE HEADER NAMES
# ============================================================

def normalize_header_name(
    value: str
) -> str:

    value_lower = value.lower()

    if "benefit" in value_lower:
        return "Benefit"

    if (
        "in-network" in value_lower
        or
        "in network" in value_lower
    ):
        return "In-Network"

    if (
        "out-of-network" in value_lower
        or
        "out of network" in value_lower
    ):
        return "Out-of-Network"

    return normalize_spaces(value)


# ============================================================
# 20. IDENTIFY STANDARD SOB TABLE
# ============================================================

def looks_like_benefit_table(
    headers: List[str]
) -> bool:

    normalized = " ".join(
        headers
    ).lower()

    has_benefit = (
        "benefit" in normalized
    )

    has_network = (
        "network" in normalized
    )

    return (
        has_benefit
        and
        has_network
    )


# ============================================================
# 21. DETECT CATEGORY ROW
# ============================================================

def is_category_row(
    row: List[str]
) -> bool:
    """
    Typical SOB category row:

        Ambulance and Medical Transport | | |

    or Azure may duplicate the merged value across columns:

        Ambulance and Medical Transport |
        Ambulance and Medical Transport |
        Ambulance and Medical Transport

    Treat both as category rows.
    """

    cleaned = [
        normalize_spaces(x)
        for x in row
    ]

    non_empty = [
        x
        for x in cleaned
        if x
    ]

    if not non_empty:
        return False

    # Case 1:
    # First column populated, remaining empty

    if (
        cleaned[0]
        and
        all(
            not value
            for value in cleaned[1:]
        )
    ):
        return True

    # Case 2:
    # Same merged content propagated across all cells

    unique_values = set(
        non_empty
    )

    if (
        len(unique_values) == 1
        and
        len(cleaned) >= 2
    ):
        return True

    return False


# ============================================================
# 22. REMOVE DUPLICATED MERGED CELL VALUES
# ============================================================

def simplify_merged_row(
    row: List[str]
) -> List[str]:

    if not row:
        return row

    cleaned = [
        normalize_spaces(x)
        for x in row
    ]

    first = cleaned[0]

    if not first:
        return cleaned

    if all(
        (not x) or x == first
        for x in cleaned
    ):

        return [
            first
        ] + [
            ""
            for _ in cleaned[1:]
        ]

    return cleaned


# ============================================================
# 23. DETERMINE TABLE PAGE NUMBER
# ============================================================

def get_table_page_number(
    table: Dict[str, Any]
) -> Optional[int]:

    page = get_page_number(
        table.get(
            "boundingRegions"
        )
    )

    if page is not None:
        return page

    for cell in table.get(
        "cells",
        []
    ):

        page = get_page_number(
            cell.get(
                "boundingRegions"
            )
        )

        if page is not None:
            return page

    return None


# ============================================================
# 24. EXTRACT TABLE BOUNDING REGION
# ============================================================

def get_table_bounding_regions(
    table: Dict[str, Any]
) -> List[Dict[str, Any]]:

    return table.get(
        "boundingRegions",
        []
    )


# ============================================================
# 25. TABLE QUALITY VALIDATION
# ============================================================

def validate_table(
    headers: List[str],
    rows: List[Dict[str, Any]],
    column_count: int
) -> Dict[str, Any]:

    issues = []

    score = 1.0

    if column_count <= 1:

        issues.append(
            "Table contains fewer than 2 columns."
        )

        score -= 0.30

    if not any(headers):

        issues.append(
            "No header row detected."
        )

        score -= 0.20

    if not rows:

        issues.append(
            "No data rows detected."
        )

        score -= 0.40

    benefit_table = looks_like_benefit_table(
        headers
    )

    if benefit_table:

        for row in rows:

            if (
                row.get("row_type")
                == "benefit"
                and
                not row.get("benefit")
            ):

                issues.append(
                    f"Missing benefit value at source row "
                    f"{row.get('source_row_index')}."
                )

                score -= 0.05

    score = max(
        0.0,
        min(
            score,
            1.0
        )
    )

    status = (
        "passed"
        if score >= 0.90
        else
        "review"
    )

    return {

        "validation_status":
            status,

        "quality_score":
            round(
                score,
                3
            ),

        "requires_review":
            status != "passed",

        "issues":
            issues
    }


# ============================================================
# 26. NORMALIZE ONE TABLE
# ============================================================

def normalize_table(
    table: Dict[str, Any],
    document_id: str,
    table_number: int
) -> Dict[str, Any]:

    table_id = (
        f"{document_id}_table_"
        f"{table_number:04d}"
    )

    grid = reconstruct_table_grid(
        table
    )

    raw_rows = grid_to_rows(
        grid
    )

    if not raw_rows:

        return {

            "table_id":
                table_id,

            "document_id":
                document_id,

            "page_number":
                get_table_page_number(
                    table
                ),

            "headers":
                [],

            "rows":
                [],

            "validation_status":
                "review",

            "quality_score":
                0,

            "requires_review":
                True,

            "issues":
                [
                    "Table contained no reconstructed rows."
                ]
        }

    header_index = find_header_row(
        grid
    )

    raw_headers = raw_rows[
        header_index
    ]

    headers = [
        normalize_header_name(x)
        for x in raw_headers
    ]

    normalized_rows = []

    current_category = None

    data_rows = raw_rows[
        header_index + 1:
    ]

    for relative_index, raw_row in enumerate(
        data_rows,
        start=1
    ):

        row_index = (
            header_index
            +
            relative_index
        )

        row = simplify_merged_row(
            raw_row
        )

        if not any(row):
            continue

        # ----------------------------------------------------
        # CATEGORY ROW
        # ----------------------------------------------------

        if is_category_row(row):

            current_category = row[0]

            normalized_rows.append({

                "source_row_index":
                    row_index,

                "row_type":
                    "category",

                "category":
                    current_category,

                "benefit":
                    None,

                "in_network":
                    None,

                "out_of_network":
                    None,

                "values":
                    row
            })

            continue

        # ----------------------------------------------------
        # NORMAL BENEFIT ROW
        # ----------------------------------------------------

        benefit = (
            row[0]
            if len(row) >= 1
            else ""
        )

        in_network = (
            row[1]
            if len(row) >= 2
            else ""
        )

        out_network = (
            row[2]
            if len(row) >= 3
            else ""
        )

        normalized_rows.append({

            "source_row_index":
                row_index,

            "row_type":
                "benefit",

            "category":
                current_category,

            "benefit":
                benefit,

            "in_network":
                in_network,

            "out_of_network":
                out_network,

            "values":
                row
        })


    validation = validate_table(

        headers=headers,

        rows=normalized_rows,

        column_count=table.get(
            "columnCount",
            0
        )
    )


    result = {

        "table_id":
            table_id,

        "document_id":
            document_id,

        "page_number":
            get_table_page_number(
                table
            ),

        "row_count":
            table.get(
                "rowCount"
            ),

        "column_count":
            table.get(
                "columnCount"
            ),

        "header_row_index":
            header_index,

        "headers":
            headers,

        "is_benefit_table":
            looks_like_benefit_table(
                headers
            ),

        "bounding_regions":
            get_table_bounding_regions(
                table
            ),

        "rows":
            normalized_rows,

        **validation
    }

    return result


# ============================================================
# 27. NORMALIZE ALL TABLES
# ============================================================

def normalize_tables(
    analyze_result: Dict[str, Any],
    document_id: str
) -> List[Dict[str, Any]]:

    tables = analyze_result.get(
        "tables",
        []
    )

    normalized = []

    for index, table in enumerate(
        tables,
        start=1
    ):

        normalized_table = normalize_table(

            table=table,

            document_id=document_id,

            table_number=index
        )

        normalized.append(
            normalized_table
        )

    return normalized


# ============================================================
# 28. ESCAPE MARKDOWN CELL VALUE
# ============================================================

def markdown_escape(
    value: Optional[str]
) -> str:

    if value is None:
        return ""

    value = str(value)

    value = value.replace(
        "|",
        "\\|"
    )

    value = re.sub(
        r"\s+",
        " ",
        value
    )

    return value.strip()


# ============================================================
# 29. BENEFIT TABLE -> NORMALIZED MARKDOWN
# ============================================================

def benefit_table_to_markdown(
    table: Dict[str, Any]
) -> str:

    output = []

    output.append(
        f"## Table {table['table_id']}"
    )

    output.append("")

    if table.get("page_number"):

        output.append(
            f"Page: {table['page_number']}"
        )

        output.append("")

    output.append(
        "| Category | Benefit | In-Network | Out-of-Network |"
    )

    output.append(
        "|---|---|---|---|"
    )

    for row in table.get(
        "rows",
        []
    ):

        if row.get(
            "row_type"
        ) != "benefit":

            continue

        category = markdown_escape(
            row.get(
                "category"
            )
        )

        benefit = markdown_escape(
            row.get(
                "benefit"
            )
        )

        in_network = markdown_escape(
            row.get(
                "in_network"
            )
        )

        out_network = markdown_escape(
            row.get(
                "out_of_network"
            )
        )

        output.append(
            f"| {category} "
            f"| {benefit} "
            f"| {in_network} "
            f"| {out_network} |"
        )

    output.append("")

    output.append(
        f"Validation: "
        f"{table.get('validation_status')}"
    )

    output.append(
        f"Quality Score: "
        f"{table.get('quality_score')}"
    )

    return "\n".join(
        output
    )


# ============================================================
# 30. GENERIC TABLE -> MARKDOWN
# ============================================================

def generic_table_to_markdown(
    table: Dict[str, Any]
) -> str:

    rows = table.get(
        "rows",
        []
    )

    headers = table.get(
        "headers",
        []
    )

    output = [

        f"## Table {table['table_id']}",

        ""
    ]

    if table.get("page_number"):

        output.extend([

            f"Page: {table['page_number']}",

            ""
        ])

    if not headers:

        return "\n".join(
            output
        )

    output.append(
        "| "
        +
        " | ".join(
            markdown_escape(x)
            for x in headers
        )
        +
        " |"
    )

    output.append(
        "|"
        +
        "|".join(
            "---"
            for _ in headers
        )
        +
        "|"
    )

    for row in rows:

        values = row.get(
            "values",
            []
        )

        values = (
            values
            +
            [""] * len(headers)
        )[:len(headers)]

        output.append(
            "| "
            +
            " | ".join(
                markdown_escape(x)
                for x in values
            )
            +
            " |"
        )

    return "\n".join(
        output
    )


# ============================================================
# 31. ALL TABLES -> MARKDOWN
# ============================================================

def normalized_tables_to_markdown(
    tables: List[Dict[str, Any]]
) -> str:

    sections = []

    for table in tables:

        if table.get(
            "is_benefit_table"
        ):

            md = benefit_table_to_markdown(
                table
            )

        else:

            md = generic_table_to_markdown(
                table
            )

        sections.append(
            md
        )

    return (
        "\n\n"
        "----------------------------------------\n\n"
        .join(
            sections
        )
    )


# ============================================================
# 32. CREATE NORMALIZED DOCUMENT JSON
# ============================================================

def create_normalized_json(
    document_id: str,
    source_md: Path,
    source_json: Path,
    cleaned_text: str,
    tables: List[Dict[str, Any]]
) -> Dict[str, Any]:

    passed = sum(

        1
        for table in tables

        if table.get(
            "validation_status"
        )
        == "passed"
    )

    review = len(tables) - passed

    return {

        "document_id":
            document_id,

        "source_file":
            source_md.name,

        "source_json":
            source_json.name,

        "document_text":
            cleaned_text,

        "table_count":
            len(tables),

        "table_validation_summary": {

            "passed":
                passed,

            "review":
                review
        },

        "tables":
            tables
    }


# ============================================================
# 33. FIND CORRESPONDING JSON
# ============================================================

def find_json_file(
    md_path: Path
) -> Optional[Path]:

    stem = md_path.stem

    candidate = (
        md_path.parent
        /
        f"{stem}.json"
    )

    if candidate.exists():
        return candidate

    # Sometimes:
    #
    # MD0000005930.md
    # MD0000005930_result.json

    candidates = list(
        md_path.parent.glob(
            f"{stem}*.json"
        )
    )

    if candidates:

        return candidates[0]

    return None


# ============================================================
# 34. IGNORE TABLE.MD FILES AS PRIMARY DOCUMENTS
# ============================================================

def is_table_markdown(
    path: Path
) -> bool:

    name = path.name.lower()

    return (
        ".table.md" in name
        or
        "_table.md" in name
        or
        "tables.md" in name
    )


# ============================================================
# 35. PROCESS SINGLE DOCUMENT
# ============================================================

def process_document(
    md_path: Path
) -> None:

    print(
        "\n=================================================="
    )

    print(
        f"Processing: {md_path.name}"
    )

    json_path = find_json_file(
        md_path
    )

    if json_path is None:

        print(
            "  SKIPPED: matching JSON not found."
        )

        return


    # --------------------------------------------------------
    # READ MARKDOWN
    # --------------------------------------------------------

    md_text = md_path.read_text(

        encoding="utf-8",

        errors="ignore"
    )


    document_id = extract_document_id(

        md_text,

        md_path
    )


    print(
        f"  document_id: {document_id}"
    )


    # --------------------------------------------------------
    # CLEAN MARKDOWN
    # --------------------------------------------------------

    cleaned_text = clean_document_markdown(
        md_text
    )


    # --------------------------------------------------------
    # READ AZURE JSON
    # --------------------------------------------------------

    with open(
        json_path,
        "r",
        encoding="utf-8"
    ) as f:

        raw_json = json.load(
            f
        )


    analyze_result = get_analyze_result(
        raw_json
    )


    # --------------------------------------------------------
    # NORMALIZE TABLES
    # --------------------------------------------------------

    tables = normalize_tables(

        analyze_result,

        document_id
    )


    print(
        f"  tables found: {len(tables)}"
    )


    for table in tables:

        print(
            "   ",
            table["table_id"],
            "| page:",
            table.get("page_number"),
            "| quality:",
            table.get("quality_score"),
            "| status:",
            table.get("validation_status")
        )


    # --------------------------------------------------------
    # OUTPUT DIRECTORY
    # --------------------------------------------------------

    document_folder = (

        OUTPUT_FOLDER
        /
        document_id
    )

    document_folder.mkdir(

        parents=True,

        exist_ok=True
    )


    # --------------------------------------------------------
    # NORMALIZED CLEAN DOCUMENT
    # --------------------------------------------------------

    cleaned_md_path = (

        document_folder
        /
        f"{document_id}_clean_normalized.md"
    )


    cleaned_md_path.write_text(

        cleaned_text,

        encoding="utf-8"
    )


    # --------------------------------------------------------
    # NORMALIZED TABLE MARKDOWN
    # --------------------------------------------------------

    normalized_tables_md = (
        normalized_tables_to_markdown(
            tables
        )
    )


    table_md_path = (

        document_folder
        /
        f"{document_id}_normalized_tables.md"
    )


    table_md_path.write_text(

        normalized_tables_md,

        encoding="utf-8"
    )


    # --------------------------------------------------------
    # NORMALIZED JSON
    # --------------------------------------------------------

    normalized_json = create_normalized_json(

        document_id=document_id,

        source_md=md_path,

        source_json=json_path,

        cleaned_text=cleaned_text,

        tables=tables
    )


    normalized_json_path = (

        document_folder
        /
        f"{document_id}_normalized.json"
    )


    with open(
        normalized_json_path,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(

            normalized_json,

            f,

            indent=2,

            ensure_ascii=False
        )


    # --------------------------------------------------------
    # VALIDATION REPORT
    # --------------------------------------------------------

    review_tables = [

        table
        for table in tables

        if table.get(
            "requires_review"
        )
    ]


    validation_report = {

        "document_id":
            document_id,

        "total_tables":
            len(tables),

        "passed_tables":
            len(tables)
            -
            len(review_tables),

        "tables_requiring_review":
            [

                {

                    "table_id":
                        x["table_id"],

                    "page_number":
                        x.get(
                            "page_number"
                        ),

                    "quality_score":
                        x.get(
                            "quality_score"
                        ),

                    "issues":
                        x.get(
                            "issues",
                            []
                        )
                }

                for x in review_tables
            ]
    }


    validation_path = (

        document_folder
        /
        f"{document_id}_validation.json"
    )


    with open(
        validation_path,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(

            validation_report,

            f,

            indent=2,

            ensure_ascii=False
        )


    print(
        "  OUTPUT:"
    )

    print(
        f"    {cleaned_md_path.name}"
    )

    print(
        f"    {table_md_path.name}"
    )

    print(
        f"    {normalized_json_path.name}"
    )

    print(
        f"    {validation_path.name}"
    )


# ============================================================
# 36. MAIN
# ============================================================

def main():

    print(
        "============================================================"
    )

    print(
        "SOB DOCUMENT NORMALIZER V3"
    )

    print(
        "============================================================"
    )

    print(
        f"Input : {INPUT_FOLDER}"
    )

    print(
        f"Output: {OUTPUT_FOLDER}"
    )


    md_files = [

        path

        for path in INPUT_FOLDER.glob(
            "*.md"
        )

        if not is_table_markdown(
            path
        )
    ]


    print(
        f"\nDocuments found: {len(md_files)}"
    )


    for md_path in md_files:

        try:

            process_document(
                md_path
            )

        except Exception as exc:

            print(
                f"\nERROR processing {md_path.name}"
            )

            print(
                str(exc)
            )


    print(
        "\n============================================================"
    )

    print(
        "NORMALIZATION COMPLETE"
    )

    print(
        "============================================================"
    )


if __name__ == "__main__":

    main()