# -*- coding: utf-8 -*-
"""pdf_parse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSgDFn8lXBpiCV4EqAjoHSL8nPRbeuNW
"""

from pathlib import Path

from docling.datamodel.base_models import InputFormat
from docling.document_converter import (
    DocumentConverter,
    PdfFormatOption,
)
from docling.datamodel.pipeline_options import (
    PdfPipelineOptions,
    TableFormerMode,
)


# ============================================================
# CONFIG
# ============================================================

INPUT_PDF = Path(
    r"C:\path\to\your\input.pdf"
)

OUTPUT_DIR = Path(
    r"C:\path\to\docling_output"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# DOCLING / TABLEFORMER CONFIG
# ============================================================

pipeline_options = PdfPipelineOptions()

# Enable table structure recognition
pipeline_options.do_table_structure = True

# Use the more accurate TableFormer model
pipeline_options.table_structure_options.mode = (
    TableFormerMode.ACCURATE
)

# Keep cell matching enabled initially
pipeline_options.table_structure_options.do_cell_matching = True


converter = DocumentConverter(
    format_options={
        InputFormat.PDF: PdfFormatOption(
            pipeline_options=pipeline_options
        )
    }
)


# ============================================================
# CONVERT PDF
# ============================================================

result = converter.convert(INPUT_PDF)

doc = result.document


# ============================================================
# EXPORT FULL DOCUMENT AS MARKDOWN
# ============================================================

markdown = doc.export_to_markdown()

markdown_file = OUTPUT_DIR / "docling_output.md"

markdown_file.write_text(
    markdown,
    encoding="utf-8"
)

print(
    f"Markdown written to: {markdown_file}"
)


# ============================================================
# EXPORT INDIVIDUAL TABLES
# ============================================================

for table_index, table in enumerate(
    doc.tables,
    start=1
):

    print(
        f"\nProcessing table {table_index}"
    )

    # Convert table into pandas dataframe
    dataframe = table.export_to_dataframe()

    # -----------------------------
    # CSV
    # -----------------------------

    csv_file = (
        OUTPUT_DIR
        / f"table_{table_index:03d}.csv"
    )

    dataframe.to_csv(
        csv_file,
        index=False
    )

    # -----------------------------
    # HTML
    # -----------------------------

    html_file = (
        OUTPUT_DIR
        / f"table_{table_index:03d}.html"
    )

    dataframe.to_html(
        html_file,
        index=False
    )

    print(
        f"Saved table {table_index}"
    )


print("\nDone.")